### ISSUE TITLE
Password protected lobbies

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#1]
Lobbies should optionally be able to have a password. The password will be asked as soon as a player tries joining the lobby.

**Comment by hija** [comment]
Why is this even required?

At least for me I think that the lobby id is unique and random enough so that no one will waste the time to bruteforce. For me it makes sense as soon as you have something like a lobbylist implemented as well, but otherwise I don't see any reason to implement this tbh.

**Comment by Bios-Marcel** [comment]
tbh, it's not
