### ISSUE TITLE
Playing with words from other languages than english

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#10]
Players should be able to play in their own language, since not every player is able to speak english. The official word-lists should be curated within the repository itself.

**Comment by AGraber** [comment]
Since this is a bit hard one due to the huge amount of languages available, this could be easily "resolved" with #11: People willing to maintain their languages will be able to provide their own client which will push its own word-lists and such, using Skribble.rs API.

**Comment by Bios-Marcel** [comment]
I am not sure how exactly you mean to do this? If a client wants to use a custom  wordlist, they can always use the "Custom Words" Field of the HTTP-Form. So theoretically this is possible anyway. And a client shouldn't be able to push a wordlist to the official backend, since they could also be doing crap. Correct me if I got this wrong.

**Comment by AGraber** [comment]
Yeah, the official wordlist would be untouchable, I probably failed to explain that correctly. The only thing missing would be a public api so others can implement clients on their own languages (talking about the actual GUI).

**Comment by Bios-Marcel** [comment]
thats planned, but not for now. I wanna have a playable game first.

**Comment by Luni-4** [comment]
Can we close this one, @Bios-Marcel?
