### ISSUE TITLE
Docker ARM support 

### ISSUE THREAD

**Issue by nicoselfhostedadventures** [scribble-rs/scribble.rs#101]
ARM Support would be nice for users that are running docker on an Raspberry Pi for example.

**Comment by Bios-Marcel** [comment]
What's wrong on armM

**Comment by SCRAFII** [comment]
When I try to run the Image I get the following error message:
`standard_init_linux.go:211: exec user process caused "exec format error"`
In the past I always got errors like this one when the image wasn't compatible with ARM, so i assumed this was the case here as well.

**Comment by Bios-Marcel** [comment]
The image is specified as linux/amd64. You can see that here: https://hub.docker.com/repository/docker/biosmarcel/scribble.rs/tags?page=1

Why can you even choose to install that? Doesn't docker check the images or something? Weird :D

**Comment by Bios-Marcel** [comment]
Anyway, seems that docker multiarch isn't super easy? Appears I gotta build them using qemu or so. While there's tools for that, I am unsure how this works with Dockerhub, because currently, it conveniently auto-updates by pulling from GitHub.

**Comment by Bios-Marcel** [comment]
@piteur Do you happen to know anything in this area?

**Comment by piteur** [comment]
hey @SCRAFII - did you test the latest Dockerfile that got merged recently?

The Dockerfile is not multi-stage, which should help with such interoperability issues.
If it doesn't, my advice will be:
1. run the `$ docker build .` command on your ARM-based workstation
2. add the compilation flag to the `builder` stage container

We may need to add an option for the docker build to pass some parameters for the architecture.

**Comment by Bios-Marcel** [comment]
I assume that there shouldn't be a compatibility in general @piteur. The probably is rather, that the image, that I pushed to dockerhub, was built on my machine (amd64) and therefore won't run on a raspberry pi.

**Comment by piteur** [comment]
In this case, we need to push the image from the CI, and build multiple images and to tag them appropriatly.

**Comment by Bios-Marcel** [comment]
Actually, I think I built the first one myself, the following ones were auto-generated by dockerhub on pushes to master. Anyway, we would need to run virtuslization in the CI, unless github suports multi-arch. I'll look at it later.

**Comment by Bios-Marcel** [comment]
It seems like GitHub supports arm builds. I assume arm is upwards compatible and we should therefore use the oldest available arm architechture? Or should we try and build images for as many as possible? I assume the benefits of having one for every version isn't very huge, right?

**Comment by maquis196** [comment]
I added arm support for another project, i found it much easier with circleci (and free as well) for dockerhub itself, im finding a working solution difficult.

**Comment by Bios-Marcel** [comment]
https://hub.docker.com/r/ckulka/multi-arch-example

It seems you can build arm images via dockerhub. I just can't test it, as i don't own any arm device right now.

**Comment by maquis196** [comment]
oh thats awesome, yeah I have a pi running docker, if you have wanna build an image ill happily test it

**Comment by andrazznidar** [comment]
Hello,
try this: https://hub.docker.com/r/andrazznidar/scribble.rs
It works on my ARM Raspberry Pi.

It is based on this:
https://www.docker.com/blog/docker-v2-github-action-is-now-ga/

Here is the one new file that makes it work:
https://github.com/andrazznidar/scribble.rs/blob/master/.github/workflows/ci.yml
