### ISSUE TITLE
pkger is not correct for our usecase

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#107]
My idea was to have a binary that's portable and can be used on any setup without requiring golang or a pack of resource dependencies at its side. However, this is exactly what pkger fails to deliver, as it has a dependency on Golang, even at runtime! Sadly I missunderstood when making use of pkger. So, what way should we go? I still wanna keep a portable binary possible, since not everyone nowadays uses docker and I am fine with that. However, as it is right now, the docker image is unusable. 

What are your thoughts on this? @piteur

**Comment by piteur** [comment]
The static binary is the preferred way IMO, and more challenging technically.
I did not find time to dig deeper on the issue, but this should not be that hard to fix IMO (the quick fix is to use full go-workspace-flavored file path right?).

Regarding the docker image, it is not broken, as files are copied on the scratch image to make it works. Did I missed something?

**Comment by Bios-Marcel** [comment]
It appears pkger has a dependency on go, even at runtime. While the binary itself contains a go-runtime, what pkger requires is a fully fledged go-binary on it's path so that it can in turn execute that to access the module system.

As far as I know the docker image shouldn't work since we are using the `golang` image as our `builder` and a `scratch` (One without golang) as the runner.

**Comment by Dr4K4n** [comment]
Just wanted to install scribble-rs via docker and can confirm that the docker image does not work. 

```
~# docker run -p 8080:8080 biosmarcel/scribble.rs
panic: exec: "go": executable file not found in $PATH: 

goroutine 1 [running]:
github.com/scribble-rs/scribble.rs/communication.readTemplateFile(0x885723, 0xa, 0x0, 0x0)
	/app/communication/init.go:73 +0x1f9
github.com/scribble-rs/scribble.rs/communication.init.0()
	/app/communication/init.go:24 +0x5d
```

**Comment by Bios-Marcel** [comment]
Tbh, we could just not use pkger for the docker image as a quickfix and then see whether there is a replacement without compromises.

**Comment by Bios-Marcel** [comment]
Okay, I replaced pkger with packr2. The docker image now works again.
