### ISSUE TITLE
Dockerhub image version management

### ISSUE THREAD

**Issue by Tijmen34** [scribble-rs/scribble.rs#108]
I assume that every master push results in a Docker build and push to Dockerhub. However, it only overwrites the older latest tag with its new version. In the event of a newly-pushed Docker image that does not work when ran (such as now), the only image that can be pulled does not work. Is it maybe possible to have some kind of version/release management? Having a version 1.0.0 or something that keeps working while latest keeps being updated would be great. :)

**Comment by Bios-Marcel** [comment]
Maybe it's time to separate develop from master

**Comment by Bios-Marcel** [comment]
The docker container should work now.

**Comment by Tijmen34** [comment]
Thanks a lot, works like a charm again! Can I help in anyway with this enhancement?

**Comment by Bios-Marcel** [comment]
You can investigate how versioning works and tell me ;)

**Comment by Bios-Marcel** [comment]
I've now split develop from master and only push stuff to master that I deem to be ready. I try to keep them rather close though.
