### ISSUE TITLE
Remove setmp command and add UI for it

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#109]
The commands `!nick` and `!start` have already been removed. Since I want to completly abandon the concept of commands and even leave it to the client how things are handled, each "command" will be a websocket command. For this feature, we'd need a new button in the top left of the canvas. On top of defining the max player count, the max clients per IP and vote kicking should also be changeable mid-game. I think changing the rest would be unnecessary.

The UI for this would just be another "center-dialog" (See templates/lobby.html) for this.

**Comment by Bios-Marcel** [comment]
@AmyrAhmady Do you happen to be interested in working on this? :)

**Comment by Bios-Marcel** [comment]
After this is done, the dependency on Bios-Marcel/cmdp can be removed :muscle:

**Comment by AmyrAhmady** [comment]
Sure, I can already imagine how it can be
a gear icon like this one: ⚙as a button which will on the right side of name change button
only visible for lobby owner, and it shows a center-dialog with elements in it, looking similar to lobby creation page http://scribble.rs (I'm talking about having the same elements and text fields, only needed ones of course!)
and as default value of text fields, we can use stored values of settings
@Bios-Marcel

**Comment by Bios-Marcel** [comment]
Introduced with 4a82c178e25947f89fa96080dd256e7e1cdd9f48
