### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#11]
A public API pretty much allows developers to create (custom) clients to connect to scribble.rs.
Eventually you have to implement an API to communicate with browser clients, which can be generalized for all software that can perform HTTP/HTTPS requests.

For example I could make a client in Unity or Godot that can be built for Android or iOS or any desktop platform, where drawing could happen at GPU level by drawing on textures.

**Comment by Bios-Marcel** [comment]
After the main Development phase is over, e.g. #1.0 has been reached, I'll consider creating a stable public API. For now I'll be focusing on functionality of the "official web-client".

**Comment by BigETI** [comment]
I want to remind you that generating HTML server sided is considered haram.

**Comment by Bios-Marcel** [comment]
HTML is no longer returned from the API and the HTML API is pretty much obsolete. You mostly need the websocket API now. Most things work by eventing. Documentation follows the next days.
