### ISSUE TITLE
Add an option to enable a trusted proxy

### ISSUE THREAD

**Issue by SZenglein** [scribble-rs/scribble.rs#111]
Http headers like "X-Forwarded-For" can be freely set by clients. Thus it is trivially easy to spoof fake addresses by simply setting this header. It should only be read when behind a trusted proxy that sets this header. 

So getting the IP from the header should be disabled by default and activated by a config option.

**Comment by Bios-Marcel** [comment]
While true, I think this might be overkill. I pretty much just wanted to fend off low-effort trolls with this. 

On top of that it might not be easy to find out which IPs to trust in an environment such as Heroku. On top of that, there are people that generally use a proxy out of privacy concerns or to get around government rulings.

Do you really think this provides enough benefit?

**Comment by SZenglein** [comment]
It's not really hard to circumvent anyway, that's true. 

But you just take either the header value or the remote Address depending on a conf.

**Comment by Bios-Marcel** [comment]
I mean, what is the real-world scenario that you have in mind for this? A specific friend asking you to allow his proxy? Or allowing the reverse proxy? Even allowing the reverse proxy in an environment as Heroku or I dunno, cloudflare might not be so easy. Addresses might randomly change, right? So, maintaining this config is probably a pain in the ass and just causes frustration. I want to keep friction low wherever possible.

**Comment by SZenglein** [comment]
The most common scenario is that a reverse proxy is used to provide load-balancing or encryption to a service. So the request goes like this: scribble.rs <- reverse proxy <- client

The reverse proxy sets the x-forwarded-for header so that the service can know the original ip of the client, because it only directly communicates with the reverse proxy. 

Now let's assume the following scenario without proxy: scribble.rs <- client  
Since the client can freely set http headers, it can fake any ip address.

So the solution is to only read the forwarded header when the service is only accessible behind a trusted proxy. The server owner should know when this is the case, so he can set the option.

So it is simply a boolean setting somewhere.

Personally, I don't have strong feelings about this, since ip limits are not that much of a security feature, but it is something to keep in mind.

**Comment by Bios-Marcel** [comment]
Yeah, I'll be closing this, as I think it would provide little to no benefit. Technically if someone really wanted this, they could slap it infront of scribble.rs, it doesn't need to be an end user application level feature.
