### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by larsfu** [scribble-rs/scribble.rs#112]
The official instance does not support https, which is a fairly easy thing to implement these days.

**Comment by SZenglein** [comment]
Reverse Proxy support was only recently added (see #57), so this is no possible.

Additionally, you are free to host your own version with https enabled.

**Comment by Bios-Marcel** [comment]
I am actually considering to move the official instance onto Heroku, as it would have built-in HTTPS and I wouldn't need to setup LetsEncrypt or go over Cloudflar.e

**Comment by Bios-Marcel** [comment]
There's now an official instance with HTTPS enabled running on Heroku, feel free to use that instead.
