### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by SZenglein** [scribble-rs/scribble.rs#114]
Output of make build:
```
$ make build
build github.com/scribble-rs/scribble.rs: cannot load /path/to/scribble.rs/packrd: cannot find module providing package /path/to/scribble.rs/packrd
```

**Comment by Bios-Marcel** [comment]
Just fon't use the makefile for now

**Comment by SZenglein** [comment]
manually executing the commands like in the Windows instructions also does not work

```
$ go run github.com/gobuffalo/packr/v2/packr2
$ go build -o scribblers .
```

go build outputs the same

**Comment by Bios-Marcel** [comment]
What OS are you on?

**Comment by SZenglein** [comment]
additional information:
```
$ go version                                 
go version go1.13.6 linux/amd64
```

**Comment by Bios-Marcel** [comment]
try:

```
rm -rf ~/go/
rm -rf ~/.cache/go-build/
```

**Comment by SZenglein** [comment]
Same error... 
I'll try doing an OS update maybe that magically fixes things.

Is there any dependency I need to install? Did you test this in a clean environment?

**Comment by Bios-Marcel** [comment]
Well, you are right, it fails. That suprises me, since the docker build didn't fail.

**Comment by Bios-Marcel** [comment]
How did you instsll go?

**Comment by SZenglein** [comment]
I installed the version from the fedora repos.

**Comment by SZenglein** [comment]
I'd try fixing it, but there is not much info online and I have zero go experience.

**Comment by Bios-Marcel** [comment]
Not via snap, flatpak or any other containerization package manager?

**Comment by SZenglein** [comment]
no no, just regular plain old dnf

**Comment by Bios-Marcel** [comment]
Looking at the path that packr produces, it totally seems incorrect to me. I am unsure why it uses absolute paths instead of package paths

**Comment by Bios-Marcel** [comment]
Okay, I found the problem cause. packr actually doesn't use go modules when using a go.mod file. Instead you have to specify that it's supposed to use go modules via the legacy environment variable `GO111MODULE`:

```
GO111MODULE = on go run github.com/gobuffalo/packr/v2/packr2
CGO_ENABLED=0 GO111MODULE=on go build -ldflags="-w -s" -o scribblers .
```

**Comment by SZenglein** [comment]
> ```
> GO111MODULE = on go run github.com/gobuffalo/packr/v2/packr2
> CGO_ENABLED=0 GO111MODULE=on go build -ldflags="-w -s" -o scribblers .
> ```

Working nicely. Would probably be best to fork it if there is no alternative, yes.

**Comment by hmenzagh** [comment]
I have the same issue but I'm not familiar with go, where should I put this to allow me to build ?

**Comment by Bios-Marcel** [comment]
Your systems commandline. Might not work if you are on windows. I think the syntax isn't the same. I am gonna fix this issue today though.

**Comment by SZenglein** [comment]
```
GO111MODULE=on go run github.com/gobuffalo/packr/v2/packr2
CGO_ENABLED=0 GO111MODULE=on go build -ldflags="-w -s" -o scribblers
```
Also try that, the spaces around the "=" are wrong

**Comment by Bios-Marcel** [comment]
#159 
#158 

Can be closed after these two.
