### ISSUE TITLE
Irrelevant chars in hints not displayed

### ISSUE THREAD

**Issue by zouglou** [scribble-rs/scribble.rs#116]
Irrelevants characters ( , -, _) in hints are currently not displayed.
"underline" values are correctly transmitted, but char code transmitted is 0, causing it not to be displayed.

One manner to correct that is to add a condition in createWordHintFor() to decide whether to transmit char code or not.
(probably not the best way, first day I write Go)

game/lobby.go - createWordHintFor()
```
...
if showAll {
	wordHints = append(wordHints, &WordHint{
		Character: char,
		Underline: !irrelevantChar,
	})
} else {
	if irrelevantChar {
		wordHints = append(wordHints, &WordHint{
			Character: char,
			Underline: !irrelevantChar,
		})
	} else {
		wordHints = append(wordHints, &WordHint{
			Underline: !irrelevantChar,
		})
	}
}
...
```

**Comment by Bios-Marcel** [comment]
Good catch, I applied your suggested change in 0415f76
