### ISSUE TITLE
Guess proximity

### ISSUE THREAD

**Issue by Crayder** [scribble-rs/scribble.rs#12]
When a player submits a guess or chat message, we could get the Levenshtein distance between the guess and actual answer. This result could be used to produce several messages hinting how close the guess was.

```
Answer: Ricky Bobby
Guess: Bobby Bouchee
Distance: 14 (-"Ricky ", -" Bouchee")
Message: "Brr... Cold", "Not even close!"
```

```
Answer: Ricky
Guess: Vicky
Distance: 1 (-"R", +"V")
Message: "One letter off!", "Scolding hot!"
```

**Comment by Bios-Marcel** [comment]
I added a check for the levensthein distance now. A distance of `1` will cause a "you are close" message.
