### ISSUE TITLE
Geometry drawing capabilities

### ISSUE THREAD

**Issue by Crayder** [scribble-rs/scribble.rs#13]
Add a setting to enable/disable advanced drawing capabilities such as drawing lines, shapes, and polygons (lines with connected points).

Disabled by default.

And the game is meant to be scrappy drawings, I'd recommend setting the draw time lower when using these.

**Comment by Bios-Marcel** [comment]
I am dropping it, sticking to the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
