### ISSUE TITLE
Words kept from previous drawer to next drawer

### ISSUE THREAD

**Issue by Tsht** [scribble-rs/scribble.rs#133]
Hello.
I tested this : list of words a,b,c,d,e,f,g
Two players (me on two different browsers)

I get random say d,e,g
Then I choose e. e is guessed.
Next drawer will have : "d, g, x", 
List of words is not totally randomised, the previous two choice (here d and g) will show again.
I don't know if it's intended, I think not because it helps the previous drawer who will know there is a chance he have to guess a word he saw in his previous list...

**Comment by Bios-Marcel** [comment]
I've solved this problem, however, the downside is, that on smaller custom word lists, of for example 10, probably most of them won't ever be picked, as they are shown once and not again. I hope this is fine.
