### ISSUE TITLE
Drawing issue

### ISSUE THREAD

**Issue by leon1995** [scribble-rs/scribble.rs#135]
Hey guys.

Does anyone has issues while dawing? When I try to draw it draws straight lines with an delay of a few second. I [recorded](https://streamable.com/zz5weu) my experience.
Does anyone know whats that about? I am using firefox.

**Comment by Bios-Marcel** [comment]
Well, that's pretty weird. Do you have especially weak hardware? I've never seen this before. Maybe it'd be interesting to see how many and when it fires the mouse events on your device.

**Comment by leon1995** [comment]
I tried it on my macbook 2018 (so no weak hardware). The problem appears on your provided heroku app, on my heroku app and when I host it locally on my macbook. I havent tried to use it on windows. Maybe its a mac-only error? I will test it tomorrow

**Comment by Bios-Marcel** [comment]
I can try simulating high ping, maybe that's what it is.

**Comment by leon1995** [comment]
I dont have a high ping either. Is a high ping even possible when I host it locally?

**Comment by Bios-Marcel** [comment]
You are right, that makes no sense. Well, technically it's possible i guess, but unlikely if you didn't set it up yourself to do that.

**Comment by leon1995** [comment]
Maybe its a macos only error? Ill try windows tomorrow

**Comment by Bios-Marcel** [comment]
Do you have any weird add-ons?

**Comment by leon1995** [comment]
When using safari i can draw like a charm (well i cant draw good but it works).
Chrome works for me, too.
I do have a lot of addons installed, but none of them (should) interferes wih the page

**Comment by Bios-Marcel** [comment]
could you please try starting in private mode where all plugins are disabled by default?

**Comment by leon1995** [comment]
Even in a private window with minimal addons it doesnt work

**Comment by Bios-Marcel** [comment]
Can you please use no add-ons at all? I can't narrow down the problem like this.

**Comment by leon1995** [comment]
I disabled all addons and can confirm that it works. ill try to find out whitch addon is the bad guy

**Comment by leon1995** [comment]
This [addon](https://github.com/kkapsner/CanvasBlocker/) is the bad guy. With it enabled I have the drawing issues.

**Comment by Bios-Marcel** [comment]
Well, then this is a non-issue :)
