### ISSUE TITLE
Add "undo"

### ISSUE THREAD

**Issue by heatherbooker** [scribble-rs/scribble.rs#138]
The "fill tool" drawing method is very dangerous...we frequently cover up a whole drawing by accident 😂 Would be nice to add a button 🔙 and/or ctrl+z support to save us from these blunders 😅

**Comment by Bios-Marcel** [comment]
I think that's part of the fun, it's by choice to not add this feature.

**Comment by heatherbooker** [comment]
Oh 😂 Nevermind then!
