### ISSUE TITLE
Start game popup does not show on self-hosted installation

### ISSUE THREAD

**Issue by romtamk** [scribble-rs/scribble.rs#139]
This is what showed up after I create a game. There is no name list.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/46883291/82574718-b8ca3e00-9bb1-11ea-8106-1f93f2120de5.png">

This line popped up in the console when I go to a link:
`2020/05/21 22:23:17 http: superfluous response.WriteHeader call from github.com/scribble-rs/scribble.rs/communication.wsEndpoint (ws.go:55)`

My system is Ubuntu 20.04, `go version go1.14.3 linux/amd64`. I built following the steps from #134.

Any help is appreciated, thank you.

**Comment by Bios-Marcel** [comment]
Hm. I am a bit confused. Does this mean that the client needlessly tried to set a header? I haven't seen this error before. Does this always happen and is there a way you can narrow it down somehow?

**Comment by romtamk** [comment]
I did some google searching and didn't find much, so I tried running scribble without using nginx's `proxy_pass` directive (which passes a web address to internal port) and I now get the start screen.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/46883291/82649771-eb247b80-9c43-11ea-8f74-ff1db605ebbf.png">

Will poke around some more.

**Comment by romtamk** [comment]
Yeah, this problem is definitely caused because of using `proxy_pass`. I can't yet figure out how to pass :8080 to http without breaking scribble, but that's another problem.

Thanks!

**Comment by SZenglein** [comment]
Did you also turn forwarding for websockets on?

Does this nginx config work?
```
location / {
        proxy_pass http://0.0.0.0:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
}
```

**Comment by Bios-Marcel** [comment]
If this is the solution, I'll add it to the readme ~

**Comment by tendant** [comment]
Below configuration works fine for me.. 

One thing to note: WebSocket related configuration needs to be before other proxy settings.

```
location / {
        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;

        proxy_pass http://0.0.0.0:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
```

**Comment by romtamk** [comment]
Ah, I had a response typed but forgot to hit send. Yes, works now over ssl after including the websocket support in nginx configuration. Thanks!

**Comment by Bios-Marcel** [comment]
I added a small section to the wiki: https://github.com/scribble-rs/scribble.rs/wiki/reverse-proxy-(nginx)

Feel free to improve it, I don't know anything about nginx ;)
