### ISSUE TITLE
Allow mounting under sub-URL

### ISSUE THREAD

**Issue by Natureshadow** [scribble-rs/scribble.rs#145]
Currently, al lresources are loaded from the root of the webserver, which does not allow proxying a sub-URL to scribble.

It would be good if it could either use relative URLs everywhere or allow configuration of the base path via environment.

**Comment by Bios-Marcel** [comment]
I'll probably do this after 1.0.0 sometime.

**Comment by Bios-Marcel** [comment]
Do we need the websocket URL to stray from the root as well? I am assuming it'd have to be `wss://HOST:PORT/XXX/v1` in that case, since the main-app could have a `/v1` too.

Also, would configuration via environment variables suffice?

**Comment by Bios-Marcel** [comment]
Moving into 1.0.0, as it seems more vital for selfhosting as I might've realized :)
