### ISSUE TITLE
Add an eye dropper tool

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#163]
An eye dropper tool allows to pick a color on a canvas.

**Comment by Bios-Marcel** [comment]
If we add a better colorpicker (circle of colors on middlemouse), do we still need this?

**Comment by BigETI** [comment]
Maybe if the selected pixel color can be selected in that menu, then not really. Some computers do not have middle mouse buttons, so they might need to opt-in into pressing on a button that is visible on the screen. Menu of that button could not include the currently selected pixel color, since you would be out of the canvas, or put the eye dropper tool into the color picker menu.

**Comment by bruh-9000** [comment]
Functionality for both an eyedropper tool via a button on the screen and via middle click would work, another solution could be allowing the user to make custom keybinds?

**Comment by Bios-Marcel** [comment]
Concrete plan:

Add the tool after the rubber. Given that there are already shortcuts assigned (Q, W, E), it would be logical to keep everything in the correct order and assign R for the eye dropper.

Besides that, it should just work like fill and do its thing on left-click only.

**Comment by Bios-Marcel** [comment]
Given that I have recently removed the color picker, I think there is no more need for this tool, as you can't pick concrete colors anymore.

Colors will most likely be dumbed down to indices anyway.
