### ISSUE TITLE
API documentation inconsistencies

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#167]
In general:

- `Wordhint` is not a word. `Word hint` would be correct.

At [https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#v1lobby](https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#v1lobby):

- Key `language` is missing the following values:
    - `french`
    - `dutch`
- Key `public` is missing.

At [https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#wordhint](https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#wordhint):

- Key `underline` has been documented as `Underline`.

At [https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#player](https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#player):

- Key `state` uses numerics instead of literals. Consider using literals for consistency reasons.

**Comment by BigETI** [comment]
There are some more things missing and things that should be written differently in the API documentation:

- `kick-vote` is undocumented
- `name-change` is undocumented
- `request-drawing` is undocumented
- `drawing` is undocumented
- All send-able message types are documented with their first characters written in upper case

**Comment by Bios-Marcel** [comment]
> drawing is undocumented

Wdym? It's in the ready-struct.

**Comment by Bios-Marcel** [comment]
K, I am renaming some field, checkout the commit when I am done, it was a bit confusing.

**Comment by BigETI** [comment]
> 
> 
> The field `ready.drawing` is now `ready.allowDrawing`

Then please document this as well, lol.

Thank you anyway!

**Comment by Bios-Marcel** [comment]
oops
