### ISSUE TITLE
Resizing window issue

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#168]
# Issue

- Draw position does not match mouse position
- Bottom menu is not positioned correctly

# How to reproduce

- Start game with a small window
- Resize window to full screen

# Tested on browsers

- Waterfox
- Chrome

**Comment by Bios-Marcel** [comment]
Nani? Can't reproduce. Outdated commit?

**Comment by BigETI** [comment]
The latest commit does not contain this bug.
