### ISSUE TITLE
System messages are conveying messages meant for players

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#170]
# Description

System messages are a good way to convey messages for logging and debugging purposes, however right now it is also being used to send messages specifically to players.

It is fine if the game is meant to be English only and if you want to show all system messages in your chat box, however problems arise when you want to localize a client or not show all system messages in a chat box.

One solution would be to define new message types for messages that should be sent to players and system internal messages categorized into three types: "information", "warning" and "error".

# Example messages from source

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L150](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L150)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L228](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L228)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L300](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L300)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L311](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L311)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L314](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L314)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L338](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L338)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L407](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L407)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L419](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L419)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L458](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L458)

**Comment by Bios-Marcel** [comment]
Well, some of these could be separate event types altogether.

**Comment by Bios-Marcel** [comment]
Leftover:

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L314](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L314)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L338](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L338)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L407](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L407)

[https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L419](https://github.com/scribble-rs/scribble.rs/blob/0ba402163d057dbd353cbdd701f92f5ece6717df/game/lobby.go#L419)

**Comment by Bios-Marcel** [comment]
Docs haven't been written yet!

**Comment by Bios-Marcel** [comment]
Docs updated: https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#v1lobby
