### ISSUE TITLE
The owner concept needs to be reworked

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#187]
Currently the owner is the only one that can start or restart a game. On top of that, the owner can change the `MaxPlayers` count. The problem is, that if the owner is gone (kicked, AFK, left), nobody else can start or restart the game. The best thing in my opinion would be to allow democratic decisions by the lobby members. This would by default be enabled in all lobbies. The setting can be changed to `false` upon lobby creation.

A decision always requires at least 80% of the lobbies players, rounding down the percentage when 80% can't be reached evenly. If there are 4 players or less, the required percentage will be 100%. However, the owner of a lobby will always have a "force" right, in order to force starting or restarting the game.

Regarding the changing of `MaxPlayers`, I think this could stay an owner thing. Even if the owner leaves, this option is usually not very important to the gameplay.

**Comment by benl96** [comment]
By democratic decisions you mean a vote for who will be the owner of the lobby?
Is there anything wrong with offering the current host the possibility to choose another host as well? 
I see the point with choosing democratic in public games but not really with private games, so both options would be nice.

**Comment by Bios-Marcel** [comment]
No, voting to start / restart the game, since that's the only thing the owner is good for.

But yeah, maybe we can add manual owner transfer as well, I think nothing's wrong with that.
