### ISSUE TITLE
Improve score calculation

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#189]
The current score calculation is somewhat arbitrary. Things such as how many players were fast and how many hints were shown aren't taken into account. I am unsure whether it's possible to get a satisfactory calculation that players preferably can even understand. Another bothersome thing right now is, that the numbers are very high. While high numbers aren't a problem, it has an odd feeling to it.

**Comment by Bios-Marcel** [comment]
I've merged the PR #191 for now. While I am not satisfied with the drawers score calculation, it's better than before.

**Comment by BBJake** [comment]
I think the calculation is actually wrong.
At the moment the user gets a higher score if he gives the answer later...

declineFactor := 1.0 / float64(lobby.DrawingTime)
baseScore := int(maxBaseScore * math.Pow(1.0-declineFactor, float64(secondsLeft)))

Example:
- DrawingTime = 120 seconds
-> declineFactor = 0,008333

- secondsLeft = 100 seconds
-> baseScore = 86

- secondsLeft = 50 seconds
-> baseScore = 131

Max/Min-Values:
Max (120 seconds): 73
Max (1 second): 198

So, maybe this one fits better:
baseScore := maxBaseScore-int(maxBaseScore * math.Pow(1.0-declineFactor, float64(secondsLeft)))

**Comment by Bios-Marcel** [comment]
You are right, I made a mistake here. When I was testing I was actually working with seconds taken and not seconds left ^^

**Comment by Bios-Marcel** [comment]
Thanks @BBJake I fixed it
