### ISSUE TITLE
AFK Status

### ISSUE THREAD

**Issue by dakyskye** [scribble-rs/scribble.rs#19]
Add a command that sets player status to Away From Keyboard. Then a player can go to toilet without a worry of being kicked cuz of being inactive. Also skip a player's turn if AFK. Clear status if a player rewrites that command or sends anything in chat.

Add an option when creating a new lobby for allowed time amount of being AFK

**Comment by MarvinKlar** [comment]
You should also have the opportunity to en-/disable the possibility to be afk or not.

**Comment by dakyskye** [comment]
> You should also have the opportunity to en-/disable the possibility to be afk or not.

Yes, i included it, didn't i?
> Clear status if a player rewrites that command or sends anything in chat.

**Comment by MarvinKlar** [comment]
> Yes, i mentioned it, didn't i?

Yeah, if you mean that by setting the 'time amount of being AFK' to 0.

Just wanted to clarify that. :)

**Comment by Bios-Marcel** [comment]
I am closing this, as you can just close your tab if you want to temporarily quit. It saves your score either way.
