### ISSUE TITLE
Scribblers needs a logo!

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#190]
Currently the text on the homepage looks a bit boring, it'd be nice to have a logo for a different touch.
I don't have a clear idea, but the current app style isn't very "scribble" like. Since I don't really plan to redesign everything now, it might be good for the logo to be somewhat clear looking, or at least not too "scribble" like.

**Comment by ngeshlew** [comment]
Hey @Bios-Marcel I'm a designer. Need any help with this?

**Comment by Bios-Marcel** [comment]
Yup, I do :)

Any contributions regarding icons / the logo are very welcome.

**Comment by ananyasen** [comment]
![image](https://user-images.githubusercontent.com/1248490/106341210-4423c500-6251-11eb-9997-5bef9962191c.png)

as a user i liked this logo

**Comment by Bios-Marcel** [comment]
Yeah, it's not bad. But skribbl.io has consistency across sll their images, which makes the overall app nicer to look at. Especially due to the fact that it's all 2 frame gifs.

So, if we are going for the same style, we should replace everything, I think.

**Comment by Crayder** [comment]
No credit needed 😬

![image](https://user-images.githubusercontent.com/9919010/106821550-5d5eb400-664b-11eb-9d66-6be879098763.png)

**Comment by Bios-Marcel** [comment]
Hm, i dunno, I kinda feel like the name should be in the logo in some way. Maybe we could mix what you've done with text :thinking: since a name + other stuff might be cool. However, it shouldn't look like "too much". I want something that's easy to memorize. Something that has recognition value, y'kno? Like, if you were to see the google colors, or the apples apple, you'd instantly recognize them, even though they are simple. Same for microsofts 4 squares.
I am a friend of simplicitly, but also like symbolism. While I think this is somewhat clashing. Maybe we can get the best out of both worlds. And maybe it's relevant to also think about this being usable as a favicon or android app icon, since @BigETI is working on an android app.

**Comment by Bios-Marcel** [comment]
This was done a while ago.
