### ISSUE TITLE
moodle integration / URL arguments

### ISSUE THREAD

**Issue by tna76874** [scribble-rs/scribble.rs#194]
Hi,

first of all: Thanks for this project!

I'm thinking about a way to integrate scribble into a moodle course. One way would be so somehow pass arguments in the url to set up the lobby and to define usernames of everybody. 

Any Ideas how to set up usernames via URL arguments for an existing lobby?

Regards

**Comment by Bios-Marcel** [comment]
Well, the username thing is the smallest problem. The question is how / WHEN is the lobby opened?

Also, may I ask why you don't just share a lobby URL with your students via e-mail / whatever way you communicate?
Would there be any benefit to integrate this into a course directly? Or do you have some kind of education in mind with this? ^^

**Comment by tna76874** [comment]
There is a possibility to generate URL parameters in moodle - this is quite handy when it comes to automatically assign names.

How about the lobby opens with default parameters when not given other options also via URL parameter? Maybe it might also possible to integrate a scribble session in a jitsi conference lit the etherpad plugin.

**Comment by Bios-Marcel** [comment]
Well, but who opens the lobby? Can there be multiple classes doing the same course with multiple different lobbies? Like, do you wanna define a lobby UUID yourself? Could lead to abuse i think. I don't want to offer that.

**Comment by tna76874** [comment]
Ok, I think I mix up different wished here.
1) simple: just an URL parameter that sets the username
2) sophisticated: lobby creation via URL, maybe with some kind of access token authentification

Actually I would be very happy if 1) would work :)

**Comment by Bios-Marcel** [comment]
Well, like said, 1 is a non problem. Putting aside the fact that usernames aren't unique.

As for 2, I am not sure what it would have to look like. I always think about abuse potential here. And i know what teens and young adults can be like ^^

I assume we'd need smth like predefined lobby profiles, so that the people doing the course can't decide upon the lobby settings. This is only important however, if the lobby is opened by the first person joining, instead of manually by the teacher.

Maybe we could for now split this into two issues, so i can already do the name thing, as that should be very easy.

**Comment by tna76874** [comment]
cool - sounds great :)

**Comment by Bios-Marcel** [comment]
hey, so I was looking into this and noticed that this already works :D

You can already pass username as a parameter in the URL. Setting the username via the URL also doesn't set the cookie, meaning it won't be remembered for future sessions. However, it can still be changed afterwards via the username change dialog.

**Comment by tna76874** [comment]
I might miss here something. I also tried to append `&username=xyz` to the lobby-link, but the name did not change.

**Comment by Bios-Marcel** [comment]
This only works when first joining a lobby not after you've already joined it.

**Comment by tna76874** [comment]
Ah now I got it. It works when a) the name was not set before in any other game (cookies) and b) only if first joining the lobby.
Would it be possible to enforce the name when first joining the lobby, independent of any name setting in a game before (cookies)?

Also it might be handy to have an option to hide the name-changing-button. scenario: A game with a larger amount of people/students where the name is set when joining the lobby and without any possibility to change the name within this lobby.

Thank you for your quick replys!

Regards

**Comment by Bios-Marcel** [comment]
Well, the students can just change their name via their first join in the URL anyways, can't they? So, no matter whether the API and the UI allow name changes, it's not bulletproof.

But yeah, we can make the cookie secondary I guess. It shouldn't cause any problems.

**Comment by tna76874** [comment]
Thank you :)
It is definitely not bulletproof - but is is quite sufficient for this purpose.

**Comment by tna76874** [comment]
One last thing would be perfect now - adding an advanced option to prevent renaming with the button within a running lobby. I just tried to add this by myself, but I'm not that familiar with go. I feel this must be just copy-n-paste from the Votekick option - but I did not manage it.

![image](https://user-images.githubusercontent.com/47271687/107880373-982fda00-6ede-11eb-8eac-d0c1e4cd9722.png)

**Comment by Bios-Marcel** [comment]
https://github.com/scribble-rs/scribble.rs/issues/207#issuecomment-798762617
