### ISSUE TITLE
Clients running on less powerful hardware could be at a disadvantage

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#199]
Clients can send as many draw commands in a given time as they want, so the problem is that if a client running on powerful hardware starts sending draw commands, clients running on less powerful hardware may lag behind or even freeze, because they are busy drawing from received draw commands.

This problem is magnified if PC users play against mobile users.
In most cases mobile hardware is way less powerful than PC hardware.

One solution would be to allow setting up rate limits for draw commands.

Another solution would be that clients may have to agree with a common tick rate dynamically.
The problem here could be that one client could report insanely low ticks per time frame, so this could be abused to disrupt the experience of other players. Maybe defining the lowest possible tick rate would be a good compromise.

**Comment by Bios-Marcel** [comment]
How would a lower tickrate help slow drawing on the mobile devices though? I assume the server would have to batch events? However, the batches would still be drawn slowly on mobile devices, right? Rate limiting the draw commands probably won't do much good either.

**Comment by BigETI** [comment]
No, clients would send with a limited tick rate to the server, so on the other side devices can keep up with rendering all the draw commands.

**Comment by Bios-Marcel** [comment]
I'll be closing this for now.

Given the current implementation of the frontend, I do not really see a problem here. Neither have I received any reports of that sort.

If anything will show up in the future, this will be looked into.
