### ISSUE TITLE
Public lobbies

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#2]
The player should be able to make his lobby public, allowing other players to join a random lobby.

**Comment by Bios-Marcel** [comment]
Instead of having a checkbox, a lobby can be created via the "public" or the "private" confirm button. This way the decision has to be made conciously and isn't just a default.

**Comment by Bios-Marcel** [comment]
A base implementation of this comes with #113

**Comment by Gioware** [comment]
List of available public lobbies (so player can join right in as soon as landing page loads) on the frontpage would be amazing.

**Comment by Bios-Marcel** [comment]
This has been merged into master now.
