### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#202]

**Comment by BBJake** [comment]
I started work on translation.
Maybe you can have a look at https://github.com/BBJake/scribble.rs/tree/Translations
It's not finished and i'm not satisfied with the engine, but maybe you could have a look...

**Comment by Bios-Marcel** [comment]
I started working on this: https://github.com/scribble-rs/scribble.rs/tree/localization

Technically, all that's left is the actual translation. And we might need a method to fill string templates, as this can't be done statically (at templating time). This might help https://stackoverflow.com/a/31007976/5841827

The major difference to your approach is that the keys aren't the original(english) string and I don't use the i18n library, as I didn't really see a need for that.

On top of that, the way this is structured, I can write a test that checks whether all keys in the non english maps are also contained in the english, because if not, this would indicate a translation error. Correctness of the keys in JS / HTML can be verified by running the templating engine once, which can also be moved into a unit test.


Feel free to give your opinion on this @BBJake :)

**Comment by Bios-Marcel** [comment]
Merged the current state into master.

Still left to debate:

* Does robot.html need to be translated? If yes, is there anything specific search engines expect?
* Should we localize sound files?
* Are there are things needed to be localized? Like dates, numbers or whatnot?
* What about the chat? Hyphenation can be localized, currently we don't have it at all. #252
