### ISSUE TITLE
Words | Split English into US and GB

### ISSUE THREAD

**Issue by maquis196** [scribble-rs/scribble.rs#208]
So a group of us play this and often were caught out by US spellings, so wanted to mirror the current en dictionary, compare it to a GB dictionary and "fix" the difference.

**Comment by maquis196** [comment]
I'm working on a small script to compare the en_us to '/usr/share/dict/british-english-large' so we can filter the difference for manual comparison (at this stage)

**Comment by Bios-Marcel** [comment]
uhm, how about we make a dictionary that supports different writings?

**Comment by maquis196** [comment]
> uhm, how about we make a dictionary that supports different writings?

You mean have single "english" dictionary that supports multiple options for a specific word? So 'Norway' would be the same everywhere but say 'Shopping Cart' would also have 'Shopping Trolley' next to it and the app would know to use the gb option by default? 

For now, would it be worth merging the eventual pr when its ready for this and then refactor the code to merge the two dictionaries into something smarter? (I ask because the sooner the above is live the better). For the end user, theyd still have English (US) or English (GB) to choose from. How is this problem handled in similar apps?

**Comment by Bios-Marcel** [comment]
https://github.com/scribble-rs/scribble.rs/issues/213 I derived a new issue

**Comment by Bios-Marcel** [comment]
Fixed with #210
