### ISSUE TITLE
Consider whether votekick and lobby settings buttons should only appear when viable

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#212]
Currently everyone sees these two buttons, no matter whether votekick is enabled or they are the lobby owner. I am unsure whether it's wise to hide them though, as it obfuscates the existence of the feature.

**Comment by BBJake** [comment]
I would hide them.
I don't like that player can votekick, so on my server the check is not set by default and the lobby settings dialog is only relevant for the lobby owner, so most of the players don't need that button.

**Comment by Bios-Marcel** [comment]
Do you think it makes sense to be able to define custom defaults? I assume you changed it in the code directly?

**Comment by BBJake** [comment]
Yes, I changed that in the code.
What do you mean by "custom defaults"? Maybe you should extract that to an extra file to make it easier to configure.

**Comment by Bios-Marcel** [comment]
Well, I guess I can offer an environment variable. This way it's also configurable via heroku with no hassle.

**Comment by Bios-Marcel** [comment]
I'd like to avoid people making forks for things such as this. Not great for the community overall I think.

**Comment by BBJake** [comment]
You're right.
I just changed this on the code on my server, but I would never commit this to my fork.
I've just done the fork for pull request on fixes and additional things ;-)

**Comment by Bios-Marcel** [comment]
I think there's be people, especially those less knowledgeable with git, that can't be arsed handling their own code and PRs properly. Ultimately reducing the willingness to contribute properly.

**Comment by BBJake** [comment]
I additional changed some other parameters (rounds / lobby language), so maybe you should make all lobby parameters configurable.
