### ISSUE TITLE
A configurable, separate timer for choosing the word

### ISSUE THREAD

**Issue by maquis196** [scribble-rs/scribble.rs#214]
having a configurable timer for choosing the word that is separate for how long you have to draw it, might be even handier in the future when you have 'word difficulty'

**Comment by Bios-Marcel** [comment]
Dupe of https://github.com/scribble-rs/scribble.rs/issues/56

**Comment by maquis196** [comment]
damn, but awesome, thanks!

**Comment by Bios-Marcel** [comment]
Haven't been too interested in this so far, sorry. But I've heard that many people want this, I might do it soon therefore.
