### ISSUE TITLE
Word set selection

### ISSUE THREAD

**Issue by Y-Less** [scribble-rs/scribble.rs#22]
![skribble rs-words](https://user-images.githubusercontent.com/991078/60469722-17b35b80-9c5e-11e9-8ba7-8f1ea9265aae.png)

**Comment by Bios-Marcel** [comment]
How about a word set gallery, where people can upvote, tag and whatnot. Could keep it simple and do stuff via copy paste.

**Comment by Bios-Marcel** [comment]
Closing in favour of #84
