### ISSUE TITLE
Proposal for a standard on how to draw shapes

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#225]
If we want all clients to behave the same in context of how they should draw on their drawing boards, then we need a standard for how to programmitcally implement drawing algorithms. We could provide pseudo code that explains how to rasterize drawable shapes.

**Comment by Bios-Marcel** [comment]
Guess we could just see what's the easiest to maintain and write while still giving best possible performance and write that pseudo code. Fill and simple lines I guess. Whether clients antialias in the end or even make a fill algorithm that takes antialiasing into account is up to them.

**Comment by SZenglein** [comment]
I think drawing board dimensions and scaling should also be specified and implemented.

For example a base board size of 1280*720 that can be scaled in full integer steps, e.g. 2560*1420. Drawing commands should always be sent in the base coordinates.


This would solve the problem of mismatching drawing commands on different screens.

**Comment by Bios-Marcel** [comment]
Meh, won't do shapes.
