### ISSUE TITLE
Shapes or stamps

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#228]
it could be fun to have geometrical shapes or stamps available for drawing.

For example geometrical shapes should have to define in a draw command what type they are, where they start, where they end, what color they have and how thick they are.

Stamps on the other hand could be just plain bitmaps. If we want to support transformation, then a client either could just send a bitmap with calculated transformation or it sends bitmaps without being transformed but including transformation information such as where to position, how to scale and how to rotate.

**Comment by Bios-Marcel** [comment]
Nope. See #13
