### ISSUE TITLE
Darktheme

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#231]
Should listen to `css-prefers-colorscheme` via media query. Requires a light icon set as well.

**Comment by fuwn** [comment]
@Bios-Marcel, have you already started taking care of this? If not, I can go ahead and see what I can do.

**Comment by Bios-Marcel** [comment]
Nope, haven't touched it yet

**Comment by Bios-Marcel** [comment]
So, I was just asking myself whether this is really worth it, if the canvas is always white anyways.
Coloring the canvas won't be possible, as it might potentially ruin certain pictures.
