### ISSUE TITLE
Allow specifying draw commands that have starting and end line width

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#241]
One reason why could be useful is that clients could for example implement drawing with pressure sensitivity, which could be used to draw lines with dynamic width.

The current implementation with single line width is not sufficient enough for this feature.

If a client does not utilize this feature, then a draw line command doesn't have to conarin its secondary line width parameter, making it optional in API.

**Comment by Bios-Marcel** [comment]
Not sure if this'd be fair for users that can't use this feature. It's probably very nieche and would give those players an advantage.
On top of that, I am not sure how much more complex this would make everything, as start and end thickness probably wouldn't be enough.
