### ISSUE TITLE
Option to define custom defaults for lobby

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#242]

**Comment by CookieCoder15** [comment]
This would be helpful! Just started hosting an instance through docker and my use case would benefit from having the max players per IP higher by default.

**Comment by Bios-Marcel** [comment]
I was planning on adding presets, so that you could pass a JSON string as an environment variable. Maybe we could use the very same preset mechanic that automagically accepts the preset called `default` as the default used on the homepage. While JSON isn't very noob-friendly, it sure makes stuff easier for me, since I wouldn't need different formats for such similar things.

I Will still try to think of a better way though, as this doesn't quite feel nice.
