### ISSUE TITLE
Random disconnection when trying to draw

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#254]
The server has dropped my connection many times yesterday and today it did it once even on my local instance, and I am not sure why the server would drop my connection when I am drawing. This doesn't occur every time, and there are no indications from the server why it would do that. This could also be an issue from ScribblersPad, but I just get a disconnection notification, no additional reason why it would drop connections.

**Comment by Bios-Marcel** [comment]
Uhm, sure you were drawing continiously? The heroku instance drops connections after 30 seconds of socket inactivity.
Other than that, I don't know why it would close the connection. I can check the logs if you give me a time.

**Comment by BigETI** [comment]
When trying to receive messages from WebSocket API
![image](https://user-images.githubusercontent.com/4518424/111883041-26551f80-89b9-11eb-9030-02e8b7493a29.png)
????

**Comment by Bios-Marcel** [comment]
So you are disconnecting yourself?

**Comment by BigETI** [comment]
Just being stupid on my side, but the issue still retains because the network stream gets disposed internally before trying to receive WebSocket messages, so that means the server is disconnecting my client for some reason.

**Comment by Bios-Marcel** [comment]
You said you had this locally. Tell me how to reproduce it and I can fix it. Because I've been using this locally for hours and hours and never had a problem.

**Comment by BigETI** [comment]
Try launching an Unity Editor instance of ScribblersPad, then try to create a lobby and draw, if your client gets disconnected, you just get something like for example
```
2021/03/20 20:33:05 Player NearlyCharmedSilkworm(721e19c3-98dc-4d40-8b25-95521f44dfb5) disconnected.
```
in the server logs, nothing more. On the client it just tells me that the WebSocket has been disposed before trying to receive WebSocket messages.

**Comment by BigETI** [comment]
And no, I do not close or dispose it explicitly, I've already checked that. It does it internally, that means something really bad happens there.

**Comment by Bios-Marcel** [comment]
Nono, I mean, how do I reproduce this without using the unity client. Because, if I can't reproduce it in the webclient, it's probably not a problem on the server side. Or can you run through it somehow with the debugger to find out more? It's just weird that this coincidentally happens the first time with the non default client, you know?

**Comment by Bios-Marcel** [comment]
Or it's some weird implementation detail of the socket lib you use :thinking:

**Comment by BigETI** [comment]
Could be entirely an issue in ScribblersPad, however I am not 100% sure about that. :/

**Comment by Bios-Marcel** [comment]
Has this been solved on your side now?

**Comment by BigETI** [comment]
I haven't encountered this issue in a while, so I guess the problem was indeed a client sided issue.
