### ISSUE TITLE
Chat container layout broken on Docker deployment

### ISSUE THREAD

**Issue by iSecret2048** [scribble-rs/scribble.rs#256]
Hello there,

I've managed to setup this project on a CentOS 8 VPS with Docker. After the initial setup, the application starts and doesn't crash.

However the front-end seems to be broken. If I fill-up the chat container with guesses, the CSS doesn't overflow as expected. It expands the whole page, creating a huge gap between the drawing tools and the canvas.

Tested on multiple browsers: Firefox (v87.0 - latest), Chrome (v89.0.4389.114 - latest) - the chat container layout is broken. It expands too much. Every resource was loaded fine, without errors.
![image](https://user-images.githubusercontent.com/16295946/113589066-3879c380-9631-11eb-9699-6e028f56c836.png)

**Comment by Bios-Marcel** [comment]
Bummer and there I thought it was perfect now. Thanks for reporting.
