### ISSUE TITLE
Scribble.rs couldn't establish a socket connection.

### ISSUE THREAD

**Issue by szabodanika** [scribble-rs/scribble.rs#280]
Hello, 
I am having trouble setting up scribble.rs on my ubuntu server. I tried the docker image, set the port to 8084, it started successfully but when starting a lobby I get "Scribble.rs couldn't establish a socket connection.". Now I built the binaries myself and ran it that way but I get the same result. It's running behind an nginx proxy, tried with and without https, always same result. I'm not sure what to do with this.

Here's my nginx config for it, everything else was done according to the readme.

```
##
# Scribblers
##
server {
  listen		80;
  server_name	scribble.my.domain;
  
  location / {
    proxy_pass		http://127.0.0.1:8084;
    proxy_set_header	Host $host;
    proxy_set_header	X-Forwarded-Proto $scheme;
    }
}
```

**UPDATE**

On the server localhost:8084 works perfectly, so it's definitely a nginx/firewall configuration error

Thanks

**Comment by szabodanika** [comment]
Okay, I remembered that Cockpit also uses web sockets and needed special settings in its nginx configuration, so I copied 4 lines and now it seems to be working, someone who knows more about nginx can probably tell if you can get it to work with fewer lines. I think adding a reminder about this in the readme would be useful.

```
...
proxy_set_header	X-Forwarded-Proto $scheme;

proxy_http_version	1.1;
proxy_buffering		off;
proxy_set_header	Upgrade $http_upgrade;
proxy_set_header	Connection "upgrade";
...
```

**Comment by Bios-Marcel** [comment]
There's a wiki page already: https://github.com/scribble-rs/scribble.rs/wiki/reverse-proxy-(nginx)

Have you tried that out? It seems a bit different. I have this from a previous error encountered by a user.
Tbh, I have absolutely no clue about nginx and don't know what's better, or furthermore right or wrong.

Either way, if necessary, update the wikipage instead and link that in the readme.

**Comment by szabodanika** [comment]
Thank you, the Wiki page seems to suggest the same solution. Added a README link in #281
