### ISSUE TITLE
Home button

### ISSUE THREAD

**Issue by ETechTechnologies** [scribble-rs/scribble.rs#288]
Please add a home button that brings you to the main page. 

Example: you are at "https://scribble.domain.org/ssrEnterLobby?lobby_id=452f9806-2764-4e6a-8053-967366d19851". Pressing the home button brings you to "scribble.domain.org".

**Comment by Bios-Marcel** [comment]
Where do you think it would fit best? I don't really see a place besides the footer. But i think that's quite uncommon.

**Comment by ETechTechnologies** [comment]
![Screenshot 2021-08-17 072634](https://user-images.githubusercontent.com/71220212/129718128-05894a05-58c3-441f-a24c-900fd8641d80.png)
I think it would look good there

**Comment by Bios-Marcel** [comment]
To be honest, I already put way too much shit there. This is clearly visible on mobile devices:

![image](https://user-images.githubusercontent.com/19377618/129948479-637aa501-4436-43d2-b5d6-357f49bf34ed.png)

Maybe if I'd replace Time and Rounds with iconography :thinking:
