### ISSUE TITLE
go  build -o scribblers ."

### ISSUE THREAD

**Issue by o0Julia0o** [scribble-rs/scribble.rs#299]
"go  build -o scribblers ." doesn´t make anything. There is no go.exe and go is no windows-command. So how do i start the game?

**Comment by Bios-Marcel** [comment]
You'll have to download go first. I've updated the build section in the readme with a link to the golang installation docs.
Try again, if you still have a problem, just comment here again.

**Comment by o0Julia0o** [comment]
Thank you. Do i have to install socket.io on my server? I don´t find this "go".

**Comment by Bios-Marcel** [comment]
You can also download it here, so you don't need to install git:

https://github.com/scribble-rs/scribble.rs/archive/refs/heads/master.zip

You have to unpack it to somewhere and change into the directory using the `cd` command.

For example if you unpack it into your user folder as `scribblers`:

```
cd %USERPROFILE%/scribblers
go build -o scribblers .
```

I might do a release soon and attach binaries, so you can download a precompiled binary.

**Comment by o0Julia0o** [comment]
Thank you. I copied the files from the master.zip in a directory.

I went in this directory with the cd-command

i used the command:
go build -o scribblers .

I get: "the command go is wrong...."

**Comment by Bios-Marcel** [comment]
Can you screenshot your terminal output?

**Comment by o0Julia0o** [comment]
It´s in german, you wouldn´t understand a word.

**Comment by Bios-Marcel** [comment]
I happen to be german

**Comment by Bios-Marcel** [comment]
You did install go by now though, right?

https://go.dev/doc/install

**Comment by Bios-Marcel** [comment]
Hey ...

Spent the day working on the automated builds ^^

You can download the latest stable version here:

https://github.com/scribble-rs/scribble.rs/releases/

As for you specifically, you'll need the the windows one I guess :D

**Comment by o0Julia0o** [comment]
Thank you. The file is infected with the Trojan.Malware.300983.susgen !

**Comment by Bios-Marcel** [comment]
Highly unlikely ^^

Here's a virustotal check: https://www.virustotal.com/gui/url/2fda592f9619f2b2d5509f1cdd7ca1acbc859d1453e19e786d163f0137dbba0d?nocache=1

**Comment by Bios-Marcel** [comment]
Are you using MaxSecure?

**Comment by o0Julia0o** [comment]
Thx. I am using virustotal.com, too: https://www.virustotal.com/gui/file/f9a100f26fb30f006d83bba1a32c686375b7150ec67cdf870aefdfd06a8ebb62

**Comment by Bios-Marcel** [comment]
Seems that the results are different depending on whether you pass the direct file URL, the file or the URL from the releases section. Either way, it's a false positive and I don't really care ^^

You are still free to build it yourself if you don't trust the GitHub binaries.
