### ISSUE TITLE
Use different color chat window messages for your correct guess vs other players correct guesses

### ISSUE THREAD

**Issue by ejhayter** [scribble-rs/scribble.rs#301]
Hopefully a minor feature request, this one came to light because when a player sets their name as "You have", the chat box prints a message indistinguishable between your correct guess and someone else's correct guess.

This may not be a problem for many people, but playing while in a zoom call, we can also hear the correct guess sounds from other players, so can get mighty confusing. And yes, we have started trolling each other using this :)

**Comment by Bios-Marcel** [comment]
Sounds simple enough, i'll look at it.

**Comment by Bios-Marcel** [comment]
I added single quotes `'You have' correctly guessed the word`. And changed the color to yellow.
