### ISSUE TITLE
Deploy on Replit

### ISSUE THREAD

**Issue by Piplup7575** [scribble-rs/scribble.rs#307]
Hello!
I'm trying to deploy this on replit using the deploy command `go build -o scribblers .` but i keep getting the error `game/words.go:4:2: package embed is not in GOROOT (/usr/local/go/src/embed)`
![image](https://user-images.githubusercontent.com/88395302/162803043-866b0ede-9cf9-4587-9807-013b5c68feb3.png)
Is there any way to fix this?
Thanks!

**Comment by Piplup7575** [comment]
Even with the dot, I still get the same error.
![image](https://user-images.githubusercontent.com/88395302/162959594-d87d8ae5-05dd-46f7-8838-6fc3068c4f65.png)
![image](https://user-images.githubusercontent.com/88395302/162959559-ab6c2cc3-05b0-44a8-ab3b-126f790d2a93.png)

**Comment by Bios-Marcel** [comment]
Oh, what go version is it running? I think you need at least go1.16.

**Comment by Piplup7575** [comment]
I think it is on 1.16, but I can't control that.
Is there any way you can look into this?

**Comment by Bios-Marcel** [comment]
you can run `go version`

**Comment by Bios-Marcel** [comment]
Anyhow, what am I supposed to do, if you don't satisfy the dependencies, that's it. I won't rewrite it all because of that :D

**Comment by Bios-Marcel** [comment]
It seems to be using 1.17.5 :thinking:

**Comment by Bios-Marcel** [comment]
Oh okay ... intersting. When you import a repo, it's version 1.14, but when you manually create a project, it uses 1.17.5.

You'll figure it out ;)
