### ISSUE TITLE
Spacing issues with large player counts (??)

### ISSUE THREAD

**Issue by AIMBOT312** [scribble-rs/scribble.rs#311]
I'm not sure how to describe it, see photos
![Screenshot 2022-04-21 135745](https://user-images.githubusercontent.com/44841254/164523194-a184538f-1578-4e97-b67a-2a60063a31bf.png)
![Screenshot 2022-04-21 135733](https://user-images.githubusercontent.com/44841254/164523202-50a6f75c-b9be-444c-a3d9-f572ccd160f3.png)
![Screenshot 2022-04-21 135719](https://user-images.githubusercontent.com/44841254/164523206-508b4fd6-4235-4ff4-849c-5176acb312a3.png)
.
![image](https://user-images.githubusercontent.com/44841254/164523308-45b9dd52-a08f-436c-acb3-0285b56c01a1.png)

**Comment by Bios-Marcel** [comment]
Yikes, must've broken this when I refactored the UI a bit
