### ISSUE TITLE
Log IP addresses

### ISSUE THREAD

**Issue by AIMBOT312** [scribble-rs/scribble.rs#313]
For moderation purposes IP address should be logged (and bannable). People keep spamming slurs.

**Comment by Bios-Marcel** [comment]
The service is ephemeral any kind of data persistence is not possible. IP bans are also easy to work around. If you want this kind of protection, you'll need either good finger printing or idcard / phone number verification, all if which go against my vwlues.

You are free to add whatever you want to a fork though.

**Comment by AIMBOT312** [comment]
Thank you for the explanation. Have a wonderful rest of your day/night :)
