### ISSUE TITLE
I clone the repo I'm getting this error 

### ISSUE THREAD

**Issue by shuence** [scribble-rs/scribble.rs#315]
[Error templating home page: html/template: "lobby-create-page" is undefined 
`func init() {
var templateParseError error
pageTemplates, templateParseError = template.ParseFS(templateFS, "templates/*")
if templateParseError != nil {
    panic(templateParseError)
}
`
Here is the function which shows the error I tried every solution available but it didn't fix.

**Comment by Bios-Marcel** [comment]
Uh, that's not enough info, I can't do anything with this. I need infos about what exactly you did and what environment you are in.

**Comment by shuence** [comment]
So I cloned the repo and run go run main.go

**Comment by Bios-Marcel** [comment]
u gotta do `go run .`

**Comment by shuence** [comment]
![image](https://user-images.githubusercontent.com/65482186/179460532-1cb11ff8-440c-4f8c-ad5a-5d33fbeffe43.png)

**Comment by Bios-Marcel** [comment]
hm, i am clueless, maybe its a windows path thing. I don't use windows.

**Comment by shuence** [comment]
Yah it fixed it it's `lobby_create.html` but in code it's `lobby-create-page` in code.

how should i proceed next nothing happening on clicking create lobby button.
![image](https://user-images.githubusercontent.com/65482186/179469431-94fd425c-84d6-4236-b012-61940795162e.png)

**Comment by Bios-Marcel** [comment]
uh, the id and the filename are different things, it works for me, that part should be right :thinking: 

Also, you've changed the code, i wouldn't know why something doesn't work :D

**Comment by shuence** [comment]
No I didn't I just editted the lobby-create html file and little bit css
