### ISSUE TITLE
Feature Request: Allow external Words-File to be used instead of default one

### ISSUE THREAD

**Issue by gbruckner** [scribble-rs/scribble.rs#323]
I would like the possibility to add an external words-file (eg. by mounting it to the docker container) to be used instead of the default one that is being built in the binary.

**Comment by Bios-Marcel** [comment]
Should be rather easy to do without changing a lot of code. Might do it over the course of this month.

**Comment by Bios-Marcel** [comment]
Close in favour of https://github.com/scribble-rs/scribble.rs/issues/84
