### ISSUE TITLE
Stats endpoint

### ISSUE THREAD

**Issue by Bixilon** [scribble-rs/scribble.rs#330]
So, an endpoint for retrieving stats would be pretty neat. Then I could monitor how many players are using my server (see #329)

Some things would be interesting:
 - count of players
 - count of lobbies
 - maybe about the score, but that'd be kinda complicated

**Comment by Bixilon** [comment]
Okay, did not see that! Thanks!

**Comment by Bios-Marcel** [comment]
I did not document it to be fair.

**Comment by Bios-Marcel** [comment]
Nice, Guess my instance won't go into sleep mode anymore then :D

**Comment by Bixilon** [comment]
Is this a problem? 

Resource wise, I looked at the container and it was barely using any cpu and just about 12M of ram. (No clue how you on demand system works) but the startup and shutdown is probably using more resources than just keeping it up. And 12M memory is nothing, the server has some gigabytes.



If you want to get access to the dashboard, just hook me up.

**Comment by Bios-Marcel** [comment]
I am using fly.io. In fly.io you can scale to 0. Meaning you won't use any compute / ram / network as long as the container is down.

However, fly.io recently changed their billing. It seems you now pay for stopped machines. So it's pricier to have a stopped free tier machine than have a started free tier machine. So maybe that's better anyway :sweat_smile:

The startup / shutdown stuff is actually pretty cheap. It's super fast too. They use firecracker. As long as your app starts fast, its near instant.

But yeah, access to the dashboard would be cool :D

I am currently checking how many concurrent players I can even handle. There was a connection limit of 25 ... I didn't know. I am increasing this after some benchmarking now. Not that there's ever that many concurrent players, since the projects hype phase was during the pandemic haha

**Comment by Bixilon** [comment]
I sent you an email :)

**Comment by Bios-Marcel** [comment]
Not sure who you sent the mail to, but it probably wasn't me :D

**Comment by Bixilon** [comment]
I sent it to your commit email: marcel.schramm@lynq.tech

**Comment by Bios-Marcel** [comment]
Oh ... That's my work email. I use the same account, but different git emails :D

Thanks haha

**Comment by Bixilon** [comment]
Oh, you  did use that email for the last few commits on scribble.rs

**Comment by Bios-Marcel** [comment]
ye, after work i just keep using the laptop. My personal one has windows right now, which sucks

**Comment by Bios-Marcel** [comment]
Hey

Just noticed something funny. I finally got around to setting up a subdomain on my domain bios-marcel.link.

I also added the subpage to google search console. Funnily your hosted site is showed as the cannonical site, so google thinks I copied your stuff i guess?

![image](https://github.com/user-attachments/assets/ec74a939-cf54-4ff8-b416-0efb066eb0aa)

Do you actually know how much traffic you receive? I am curious :D

**Comment by Bixilon** [comment]
Hi Marcel,
I just fixed the grafana poller, it somehow was broken. I actually don't think I am receiving much traffic, not sure.


How would I change this? How can I make your instance the canonical url? I just opened the google seach console and had to reverify my domain, so all stats are gone.

**Comment by Bios-Marcel** [comment]
No clue honestly. I am just getting started with all this stuff :D

Will see if it disappears soon, if not, I'll investigate deeper.

**Comment by Bixilon** [comment]
I acutally have no clue about search index (optimizations). Should care about it. But I am just doing my projects for fun and for myself, so I don't profit that much from getting found online.

But if I can do anything about it, hook me up.

**Comment by Bios-Marcel** [comment]
Yeah fair.

Good to know you are down to fix it though :D

While I don't want to profit from it right now, I was considering building a bigger community. So I guess I gotta up my web game.

I'll hit you up then if I find out anything!

**Comment by Bixilon** [comment]
I am I don't profit from it. You do profit from it, somehow. There is a link to the github repo on my page too.

But yes, *your* project, don't have that much to do with it (except monitoring the instances and providing server resources). imho its fair if your is the official instance (and you get the search credit on google).

What do you mean with *building a bigger community*? Higher player count?

**Comment by Bios-Marcel** [comment]
Yeah, I'd just love to have more people actively playing in public lobbies.

From time to time people playand I join the lobbies, it's good fun.

I also made a discord now and was trying to get it working as a discord activity.

We'll see how it plays out. But with higher player counts, my hosting probs won't last long, so I might try and get donations for better hosting. It runs a 256MB ram machine with 1 shared vcpu core 🤣

**Comment by Bixilon** [comment]
I used to play a lot a couple of years ago, beacuse skribbl.io is so bloated and broken on mobile devices. But not really playing it at all atm.

Don't have (and want) discord, so not joining :)

I think my instance is allowed to use 4 cpus and 1GB of memory (I can increase it, when needed), in idle the container is using 30MB. Traffic is also not that high, 1.3GB outgoing in 13 days. Pretty chill. Good job on not using resources!

I mean I am not donating money, I am donating server resources. No need for you to stack up rn. :laughing:

**Comment by Bios-Marcel** [comment]
Yeah, no worries, didn't want to get you to join 😁 
I figured many people here wouldn't like discord.

Yeah, its great that you host an instance, I am thankful for all community instances!

It'd be cool if I could distribute traffic to community instances automatically. I am slowly trying to make everything scalable somehow, but still keep simple self hosting functional.

**Comment by Bixilon** [comment]
I mean the only really simple option is to have one coordinator, that checks what instance you get to. Then you just redirect to that instance and then create the game there. That would be really simple. You would loose public lobbies with that on a central instance.

**Comment by Bios-Marcel** [comment]
Yeah, i'd need some type of public lobby server that holds all the addresses I guess and can be used as opt in or so. I dunno. I don't want to make the setup to fragile though.

**Comment by Bixilon** [comment]
![Screenshot_20250109_153020](https://github.com/user-attachments/assets/55720d02-96d3-43bc-8a1f-0aed781bfbba)


Those are the stats from the last 2 weeks or so, as you see your instance (red) gets most traffic. scribble.bixilon.de and  pictionary.yilingai.com get some. 

Overall traffic is pretty low, there were never more than 20 players online at a time on one instance.

**Comment by Bios-Marcel** [comment]
Ah cool, interesting insight. Where did you even find the other instances?

I gave up on the google search thing btw. Absolute garbage experience :D

**Comment by Bixilon** [comment]
I just googled. You can access those graphs with the grafana credentials I gave you some time ago.

Yes, SEO is so fucked up and trashed,

**Comment by Bios-Marcel** [comment]
As for my setup, it shuts down if no traffic is received and then it needs a couple of seconds to be properly reachable again (its a lil buggy). But it shouldn't freeze for longer than 20s

**Comment by Bixilon** [comment]
Yes, I know that. That is not the issue on with the crawler. The crawler was sometimes (really no clue why) stuck in the method and it froze the complete program (collecting all sites, putting the data into influxdb and then grafana gets the data from influxdb at any later time). I did not configure any network timeouts and it seems like if traffic is dropped from network `requets.get` is never timing out and in a waiting state forever. I (hopefully) fixed that issue, so no blank stats should be visible in grafana.
