### ISSUE TITLE
Display Version

### ISSUE THREAD

**Issue by kovmir** [scribble-rs/scribble.rs#340]
Can you please show app version on the web page? Useful for reporting and seeing whether you are up to date.

**Comment by Bios-Marcel** [comment]
Related to #337 

I'll probably move this into the help menu as well.

**Comment by Bios-Marcel** [comment]
havnet pushed yet, but check here: https://scribblers.fly.dev/

its in the footer now, but the lobby footer was moved into the help dialog

**Comment by kovmir** [comment]
Great, exactly the thing I wanted.
