### ISSUE TITLE
Color picker has an inconsistent look and feel on chromium

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#350]
On chromium, there is a default padding that is smaller than it should be.

Manually setting a padding on `#color-picker` doesn't have the desired result. Hence this has so far only been done for firefox.

**Comment by Luckyjoseph** [comment]
Hi can I work on this issue. can you assign this to me @Bios-Marcel

**Comment by Bios-Marcel** [comment]
Sure thing :)

**Comment by Bios-Marcel** [comment]
The color picker has been removed!
