### ISSUE TITLE
Hold Shift to draw straight line

### ISSUE THREAD

**Issue by theevilphysicist** [scribble-rs/scribble.rs#36]
Hold Shift to draw straight line

**Comment by Bios-Marcel** [comment]
I am not sure whether this would ruin the "shitty drawings" aspect of the game, which is what I believe makes the game way more charming. As the drawings look more precise, that could kinda make the game look more boring.

**Comment by theevilphysicist** [comment]
I mean if this is provided as an option, People who want to go with straight lines can use it and people who want the "shitty" lines aspect can avoid it ?? It wouldn't hurt to have it as an option. 
also, fill tool when?

**Comment by Bios-Marcel** [comment]
I am just gonna close this, as I've decided that this feature goes against the idea of the game. Also, the fill tool has been implemented.
