### ISSUE TITLE
Go beyond the 24-player limit?

### ISSUE THREAD

**Issue by shrrravan** [scribble-rs/scribble.rs#361]
<img width="580" alt="image" src="https://github.com/user-attachments/assets/4a9c73ee-b49c-4183-89eb-ceb30e5e9e12">

Firstly, I genuinely appreciate the effort you’ve put into this. I absolutely love the game! :)

I’d like to play it with all my colleagues, and there are approximately 50 of us. Is there any possibility that you could increase the maximum number of players allowed in any of the hosted instances?

**Comment by Bios-Marcel** [comment]
Yeah, tbh, the max player limit was kind of arbitrary. I'll put it to 100 or so :)

**Comment by shrrravan** [comment]
Awesome! Thank you!! 🥳

**Comment by shrrravan** [comment]
Ah, I just read your edit. Let me create a PR right away then, so we can test it out.

Full disclosure: I'm hosting an office party on the 4th of Dec, so I'm hoping this feature gets added before that. 😅

**Comment by Bios-Marcel** [comment]
Don't make a PR. I am gonna make this configurable real quick. I don't want to change hardcoded stuff.

I want to give people the option to just put things to 1 million IF they really want :)

**Comment by shrrravan** [comment]
Ah gotchu ✌️

**Comment by Bios-Marcel** [comment]
Comitted and tagged: 242c80096916b3a19cfccd61ba8a460608507ac6

Deployment done. Enjoy.

Feel free to give feedback on how well it performs :)

Also, with 50 people you might want to only play with rounds "1" 🤣

**Comment by shrrravan** [comment]
Thanks a lot!! 🤗

**Comment by Bios-Marcel** [comment]
Hey, I previously added a connected_players metric to see how well everything scales.

But it looks like you ended up not playing or played with a lot less people. Out of interest, was there any issue or was it non-technical reasons? 😄

**Comment by Bios-Marcel** [comment]
Ah, bummer ^^

I mean, I can technically make virtual stress tests to test the server throughput easily.

Harder to do with the UI though. At least I don't have much experience with such performance stuff for the frontend. I am not a web developer.

I might try and streamline the stress test tooling a bit. I think I wrote something here, but its not very good:

https://github.com/scribble-rs/scribble.rs/blob/master/tools/simulate/main.go

I am not really sure what'd be a good format here. It'd be cool to have something that randomly sends different types of events.

**Comment by Bios-Marcel** [comment]
Can you use playwright to measure latencies accross different browser instances? Like how fast does a click propagate to another browser instance?

**Comment by Bios-Marcel** [comment]
Hm, I see 🤔 

I wonder if it'll lead to confused if I change it now. I'll think about it.

I'll fix the max IP thing, thanks for telling.

**Comment by Bios-Marcel** [comment]
Actually @sh-ravan , the max player per ip limit can also be override via the settings. So everything is fine ig?

**Comment by Bios-Marcel** [comment]
Yeah, i forgot to set it on the official instance, its a server setting. I might have to adjust the config docs a bit :D
