### ISSUE TITLE
Scoring scheme defferring according to the rank of guesser

### ISSUE THREAD

**Issue by driftywinds** [scribble-rs/scribble.rs#362]
Currently, the first person to guess and the second person to guess have very little change in the scores they achieve, but in the skribbl.io game, part of what makes guessing first incentivized and fun is the fact that you get close to 2x the points than the second person to guess does even if fit is a millisecond later. 

Could this be implemented? Imo it would improve the quality of life of this game a lot and make it a lot more fun too.

**Comment by Bios-Marcel** [comment]
Hm, I think I wouldn't want to make the scoring differences too drastic.

The reason Why I went for this approach, was to keep giving people that aren't always super fast a chance to still win.

I could increase the differences a bit more or even offer a setting to specify the scoring algorithms.

**Comment by driftywinds** [comment]
> Hm, I think I wouldn't want to make the scoring differences too drastic.
> 
> The reason Why I went for this approach, was to keep giving people that aren't always super fast a chance to still win.
> 
> I could increase the differences a bit more or even offer a setting to specify the scoring algorithms.

Yes, even a toggleable option to have such a scoring scheme would be a godsend!!

**Comment by Bios-Marcel** [comment]
Started work here:

https://github.com/scribble-rs/scribble.rs/pull/363

**Comment by driftywinds** [comment]
> Yo @driftywinds
> 
> Changes are done. The branch isn't merged yet, BUT I have already deployed it! I'd be happy if you could test it. There's now two algorithms (its the same algorithm ... but y'kno, I made the numbers configurable).
> 
> One is `chill`, which is basically even less competitive than the old one and one is `competitive` which is more competitive than the old one.
> 
> I tried to get some contrast, but not make it too hard.
> 
> The interface is abstract enough to allow easily adding new algorithms now.

lets gooooo, the changes are live on your own instance right? I'll check em out rn

**Comment by Bios-Marcel** [comment]
Yup, the https://scribblers.fly.dev one

**Comment by Bios-Marcel** [comment]
Hey #365 is done. Feel free to tell me if you think it works out fine with the competitive scoring.

I was thinking maybe the decline curve should be a tad different, so that it only starts declining after 5 seconds of the word being chosen? Technically 5 seconds COULD be enough to draw something.

**Comment by driftywinds** [comment]
> Hey #365 is done. Feel free to tell me if you think it works out fine with the competitive scoring.
> 
> I was thinking maybe the decline curve should be a tad different, so that it only starts declining after 5 seconds of the word being chosen? Technically 5 seconds COULD be enough to draw something.

Could you make a release so I can test it out? Yes I think the 5 second idea sounds great!

**Comment by Bios-Marcel** [comment]
Its already deployed, no?

**Comment by driftywinds** [comment]
> Its already deployed, no?

It's only deployed on your instance, because there isn't an official docker image release after 0.8.18. If you make a release my instance will also implement the changes automatically

**Comment by Bios-Marcel** [comment]
nvm, just realised i broke smth ... important

**Comment by Bios-Marcel** [comment]
Kk ... fixed, tagged and deployed :D
