### ISSUE TITLE
Cache Busting incorrect for JS

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#373]
We currently use the cache busting hash that is calculated with resources.

However, the templates aren't in the resources folder. We should instead just calculate a per file cache busting number. This will also increase cache misses in the future.

**Comment by Bixilon** [comment]
How about appending the hash (or the first x digits) to the filename? Then you always load the corrent one. Generate it automatically and rename the files during build and patch it in. Then you will not forget to increase the number and if you revert, you can reuse the old cache.

**Comment by Bixilon** [comment]
Oh, nevermind. That is exactly what you do. Did only read part :)

**Comment by Bios-Marcel** [comment]
Yup, right now it's /filename?cache_bust=...

This way the path can still be read and its simple to implement. I also added a fallback, in case i ever forget to hash anything or so :D
