### ISSUE TITLE
Autoselect word after X seconds

### ISSUE THREAD

**Issue by MarvinKlar** [scribble-rs/scribble.rs#39]

**Comment by Bios-Marcel** [comment]
I decided against that, since it's fucking annoying if you need more time to think. You have the choice, either choose faster or have no time for drawing.

**Comment by MarvinKlar** [comment]
Okay, then we have to fix the message of the end of the game, which annonces the guessing word. Cause this is not set at the end of the game, if it's not selected. The message could be something like "The player didn't selected a word" or similar.

**Comment by Bios-Marcel** [comment]
The text should be `Round over. No word was chosen.`
