### ISSUE TITLE
Limiting Max-Players, Drawing-Time and Rounds

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#4]
On lobby creation the creator should be able to decide how many players the lobby can hold at max, how much time a player has to make his drawing and how many rounds there should be.

Progress:
  - [x] Rounds
  - [x] Max-Players
  - [x] Drawing time

**Comment by Crayder** [comment]
Possibly a bit extra but possibly an option for hint intervals and toggling guess proximity messages (or a limit to say a Levenshtein distance of 3 and less, or 0 to disable).

**Comment by Bios-Marcel** [comment]
What do you mean by `Possibly a bit extra`.

Being able to disable or enable hinting sounds fine. Deciding on the levenshtein distance sounds a bit too power user like to me ^^ And I think anything above 1 probably breaks the game.
