### ISSUE TITLE
Show your score from this round

### ISSUE THREAD

**Issue by AdamsLT** [scribble-rs/scribble.rs#42]
As a player I want to see how many points I got after answering, so that I know how quick I need to be to catch up, how much faster/slower I was than anyone else.

- If you implement it as a system message 
Pros - can at a glance see who was faster, the message persists through rounds
Cons - useless information spam for others
Solution for con - scribbl.io does this and it doesn't seem problematic

- If you implement it as an extra bit of information in the player card
Pros - Looks cleaner, uses some of the whitespace on the cards
Cons - Likely will be wiped between rounds (if I was last I would not be able to see the data, etc) Solution for con - persist between rounds with a different color shade and disappear after the next round/guess or appear for a set timer, e.g. 10secs; queue the next data blob if you answer the next round quickly and the previous one is still active

**Comment by Bios-Marcel** [comment]
I'd rather go for adding it to the player card and resetting it every round. I don't think that you really care how many points you got 3 rounds ago.

**Comment by Bios-Marcel** [comment]
What about this:
![preview](https://user-images.githubusercontent.com/19377618/61541307-b4883e00-aa3f-11e9-8b49-0e7f44cbda7b.png)
