### ISSUE TITLE
Installation and running - help needed

### ISSUE THREAD

**Issue by wlcina** [scribble-rs/scribble.rs#46]
Hello, I prepared ubuntu virtual machine, and tried to run my own Scribble server at local lan.

First, I downloaded as described, but some errors appeared:
```
@ubuntu:~$ go get github.com/scribble-rs/scribble.rs
go: finding github.com/scribble-rs/scribble.rs latest
go: downloading github.com/scribble-rs/scribble.rs v0.0.0-20191020175806-9e43418cec98
go: extracting github.com/scribble-rs/scribble.rs v0.0.0-20191020175806-9e43418cec98
go get: github.com/scribble-rs/scribble.rs@v0.0.0-20191020175806-9e43418cec98: parsing go.mod:
	module declares its path as: github.com/Bios-Marcel/scribble.rs
	        but was required as: github.com/scribble-rs/scribble.rs

```
Later, I installed go-lang with, "sudo apt  install golang-go"
Then I entered folder and tried to run Scribble by:
@ubuntu:~/Projects/Skrible/pkg/mod/github.com/scribble-rs/scribble.rs@v0.0.0-20191020175806-9e43418cec98$ go run main.go
Then I tried to open in Firefox following:  localhost, localhost/lobby.html, localhost/create_lobby.html, but none is working, any help?

**Comment by Bios-Marcel** [comment]
Looks like I made a mistake. I'll fix it by tomorrow. Thanks for the report.

**Comment by Bios-Marcel** [comment]
K, I fixed it and updated the instructions: https://github.com/scribble-rs/scribble.rs#building

It's a bit annoying right now, as this project isn't very mature, since I am currently focusing on other stuff.
Anyway, if you have other problems, tell me. And if it works now, please close this issue :D

**Comment by wlcina** [comment]
Hello, tried from scratch, but no luck again (I am using virtual machine with Ubuntu). 
Clean install.
Installing github (sudo apt-get install git)
Installing curl to get go-lang (sudo apt install curl)
Download latest go-lang (curl -O https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz)
- extracted gzip
setup permissions: sudo chown -R root:root ./go
Moved go-lang to correct dir: sudo mv go /usr/local
Edited profile: sudo nano ~/.profile
by adding 2 lines at bottom:
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
save and reload profile:
source ~/.profile
Rebooted the VM (dont ask me why, it just does not recognized go-lang is installed)
downloaded Skrible: go get github.com/scribble-rs/scribble.rs
# github.com/scribble-rs/scribble.rs
go/src/github.com/scribble-rs/scribble.rs/lobby_logic.go:170:34: multiple-value uuid.NewV4() in single-value context
go/src/github.com/scribble-rs/scribble.rs/lobby_logic.go:198:28: multiple-value uuid.NewV4() in single-value context
go/src/github.com/scribble-rs/scribble.rs/lobby_logic.go:199:28: multiple-value uuid.NewV4() in single-value context

**Comment by Bios-Marcel** [comment]
That looks like you are executing it with go 1.10 :thinking: 

Run `go version`. If it doesn't show the one that you manually downloaded, you gotta deinstall the one you installed with APT.

**Comment by wlcina** [comment]
@ubuntu:~$ go version
go version go1.13.5 linux/amd64 

that setup variable GO111MODULE=on is from instructions of yours.

**Comment by Bios-Marcel** [comment]
Try running:

```
git clone https://github.com/scribble-rs/scribble.rs.git
cd scribble.rs
go build . -o scribblers
./scribblers
```

That should start the server.

To keep it running, start it in a `screen` session (A linux tool to keep bash processes running after disconnecting)

**Comment by wlcina** [comment]
```
@ubuntu:~/scribble.rs$ go build . -o scribblers

go: downloading github.com/Bios-Marcel/discordemojimap v0.0.0-20190428151516-84c5d00d1ea1
go: downloading github.com/dustinkirkland/golang-petname v0.0.0-20190613200456-11339a705ed2
go: downloading github.com/agnivade/levenshtein v1.0.2
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/Bios-Marcel/cmdp v0.0.0-20190623190758-6760aca2c54e
go: extracting github.com/satori/go.uuid v1.2.0
go: extracting github.com/Bios-Marcel/cmdp v0.0.0-20190623190758-6760aca2c54e
go: downloading github.com/gorilla/websocket v1.4.0
go: extracting github.com/dustinkirkland/golang-petname v0.0.0-20190613200456-11339a705ed2
go: extracting github.com/gorilla/websocket v1.4.0
go: extracting github.com/Bios-Marcel/discordemojimap v0.0.0-20190428151516-84c5d00d1ea1
go: extracting github.com/agnivade/levenshtein v1.0.2
go: finding github.com/Bios-Marcel/cmdp v0.0.0-20190623190758-6760aca2c54e
go: finding github.com/Bios-Marcel/discordemojimap v0.0.0-20190428151516-84c5d00d1ea1
go: finding github.com/agnivade/levenshtein v1.0.2
go: finding github.com/dustinkirkland/golang-petname v0.0.0-20190613200456-11339a705ed2
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/satori/go.uuid v1.2.0
can't load package: package -o: malformed module path "-o": leading dash
can't load package: package scribblers: malformed module path "scribblers": missing dot in first path element
```
After that ./scribblers is unknown command

**Comment by Bios-Marcel** [comment]
sry, meant go build -o scribblers .

**Comment by wlcina** [comment]
Great !!! now it works :D

**Comment by Bios-Marcel** [comment]
FYI, the game can be started with `!start` via the chat. And the word pool is pretty small, if you have word suggestions, feel free to make a PR!
