### ISSUE TITLE
Name changing shouldn't be allowed if a word has already been chosen

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#47]

**Comment by L-as** [comment]
Why not?

**Comment by Bios-Marcel** [comment]
I've had leople change their name to the solution. An option would be to do the rename on the next turn.

**Comment by Bios-Marcel** [comment]
I've realized that if people want to cheat, they can purposefully write down the word with typos either way. For this stuff, we got a kick function, therefore I am closing this.
