### ISSUE TITLE
Option to add Word List files from desktop

### ISSUE THREAD

**Issue by Mohinem** [scribble-rs/scribble.rs#48]
Suppose I copy-paste a word list, I will be able to glance through words, which will make game unfair. So instead of that, it will be nicer if we can add a file containing list of words.

**Comment by Bios-Marcel** [comment]
I am not sure whether this provides a huge benefit. It doesn't sound worth implementing. Anyway, I still have bigger plans for the word lists. At some point I plan to have a gallery where you can choose words from. I'll be closing this for now, sorry.
