### ISSUE TITLE
Game can't start

### ISSUE THREAD

**Issue by xWafl** [scribble-rs/scribble.rs#49]
When making a private lobby with my friends, !start in the chat section doesn't start the game. In fact, no messages show up at all. Also, new players joining doesn't emit to the other players, meaning that the creator of the lobby only sees 1 person until they refresh.

**Comment by Bios-Marcel** [comment]
Sounds like your websocket connection is being blocked. Can you check the developer console for error output?

**Comment by xWafl** [comment]
It just says Attempting Connection... and then Successfully Connected. No error messages.

**Comment by Bios-Marcel** [comment]
Well, i can't really debug this from afar, as I never had this problem

**Comment by Bios-Marcel** [comment]
This maybe be related to #57

**Comment by hija** [comment]
Yes, it is indeed related. I am pretty sure, that @xWafl is using an https connection.

@xWafl: Could you try to fix that by changing https://github.com/scribble-rs/scribble.rs/blob/925ecc42c447d6f99843b18ea289637498e4f18b/lobby.html#L187

to 

```
const socket = new WebSocket("wss://" + location.hostname + "/ws?id={{.LobbyID}}");
```

or if you do not use port 80 then try using instead:

```
const socket = new WebSocket("wss://" + location.hostname + ":YOURPORT/ws?id={{.LobbyID}}");
```

If this does not work, please report your game environment (webserver etc.) so it's easier to find out the problem :-)

**Comment by Bios-Marcel** [comment]
I'll be closing this, as technically everything should be working fine.
