### ISSUE TITLE
Can't draw anything

### ISSUE THREAD

**Issue by Luni-4** [scribble-rs/scribble.rs#51]
Unfortunately I can't draw anything when I open a new lobby. I'm currently using `Mozilla Firefox 74.0` on `Ubuntu 19.10`.

**Comment by Luni-4** [comment]
Ok, the problem was mine. I haven't enabled drag and drop gestures. Sorry for the trouble!

**Comment by Bios-Marcel** [comment]
Could you elaborate on this? I never heard about this? I am simply Using Mouse-Listeners.

**Comment by Luni-4** [comment]
Practically I haven't enabled the drag and drop gestures on my touchpad, so when I had launched the `!start` command, I couldn't draw anything. It was an error on my part, completely unrelated to `scribble`.
