### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by josemmc95** [scribble-rs/scribble.rs#52]
It freezes when you create the room and the time left is infinity.

![Captura de pantalla 2020-03-15 a las 23 24 56](https://user-images.githubusercontent.com/62221854/76711922-371ee580-6714-11ea-9f77-ea4dca8033cc.png)

**Comment by Bios-Marcel** [comment]
i should add a button haha

**Comment by josemmc95** [comment]
It’d be so nice!

I’m translating the words file, which means the end suffixes?

Thanks!
