### ISSUE TITLE
Add start and nick buttons

### ISSUE THREAD

**Issue by Luni-4** [scribble-rs/scribble.rs#54]
In addition to the `!start` and `!nick` commands, it would be helpful for users to press buttons.
They could be added inside the red circles, in this way the content of the green circle is no more necessary.

![Senzanome](https://user-images.githubusercontent.com/12353765/77015543-608a7c00-6975-11ea-9e35-3423ba3fd77d.png)

**Comment by Bios-Marcel** [comment]
I considered just making the name clickable and putting the start button in the middle of the canvas when the game hasn't started. That way it would feel more natural than randomly clicking buttons. However, I am not sure whether people would understand that their name is clickable. Maybe the own name could be underlined or so, or just a textbox rightaway.

**Comment by Luni-4** [comment]
> I considered just making the name clickable and putting the start button in the middle of the canvas when the game hasn't started. That way it would feel more natural than randomly clicking buttons.

I like this one, it's much better than my first idea. 

>However, I am not sure whether people would understand that their name is clickable. Maybe the own name could be underlined or so, or just a textbox rightaway.

Perhaps under the kick button with a label that appears when you hover over it?

**Comment by Bios-Marcel** [comment]
Hey, can you please put the name change topic into a new issue?
