### ISSUE TITLE
The timer should start after a word has been chosen

### ISSUE THREAD

**Issue by Luni-4** [scribble-rs/scribble.rs#56]
While I'm choosing a word to draw, the timer is already running. It should start as soon as a word has been chosen.

**Comment by Bios-Marcel** [comment]
This was a design decision and i did it in order to keep people from taking too long for choosing a word. If you want more time, simply increase the time on lobby creation. If that's not good enough, then try explaining to me why, because to me it seems to solve the problem.

**Comment by Luni-4** [comment]
Oh, now I see your approach, but in that way we are subtracting precious time to the players. Perhaps we could establish a maximum time set for choosing a word, e.g. 20 seconds, and when that time runs out, the first, or a random, word among the three is chosen.

**Comment by Bios-Marcel** [comment]
I guess, I could just add a second timer. What really annoyed me on skribbl.io, was that you only had a certain amount of time to pick before it autopicks, but you couldn't see the time ... I guess this would be a solution then.

**Comment by Bios-Marcel** [comment]
K, the drawing time specified in the lobby will then only be drawing time and the word-choice time will be a fixed amount of 20 seconds and display within the word choice dialog

**Comment by Luni-4** [comment]
> I guess, I could just add a second timer. What really annoyed me on skribbl.io, was that you only had a certain amount of time to pick before it autopicks, but you couldn't see the time ... I guess this would be a solution then.

I agree with you, it's pretty annoying not knowing the time to choose a word.




> K, the drawing time specified in the lobby will then only be drawing time and the word-choice time will be a fixed amount of 20 seconds and display within the word choice dialog

Thanks a lot! :)

Do you think we should display the chosen word to the user? For example using a dialog window that says something like this: The chosen word is `scribble`!

**Comment by Bios-Marcel** [comment]
it is displayed at the top

**Comment by Luni-4** [comment]
Sure, I was thinking to something to signal the user that the time is run out, but since one can always see the word at the top, let's leave it as it is. I agree with you.
