### ISSUE TITLE
Support of wss

### ISSUE THREAD

**Issue by hija** [scribble-rs/scribble.rs#57]
I think we should use wss instead of ws if the website was served via https.
Otherwise most browsers will not allow the websocket connection.

Workaround for right now: I got scribble.rs running by replacing "ws" with "wss" in lobby.html,

**Comment by Bios-Marcel** [comment]
Well, that doesn't work for me.

**Comment by hija** [comment]
Yeah, probably because you are not serving a TLS certificate, do you?
I have the following setup:

* Scribble.rs listening on 8080
* Nginx server listening on 80 and using TLS/HTTPS

Then I changed ws --> wss. Additionally, I had to remove the port, because nginx was listening on port 80 and not on 8080. 

Changing ws --> wss per default will not work as not everyone wants to use certificates and has a valid certificate.

Maybe I will write a tutorial on how to use scribble.rs with nginx as reverse proxy. However, right now I have to modify the .html (as said: ws --> wss and remove 8080) and thus I think it would be an improvement if the instance would detect this on its own.

**Comment by hija** [comment]
Or: That we can ask the scribble.rs instance to deliver the file with wss, since it probably does not know that it is running behind a reverse proxy.

**Comment by Bios-Marcel** [comment]
Well, i'll look into this

**Comment by hija** [comment]
https://github.com/plack/Plack/wiki/How-to-detect-reverse-proxy-and-SSL-frontend

The X-Forwarded variables should be set if you are using a reverse-proxy, so I think this could work out :)

**Comment by hija** [comment]
I want to second this again. I realized that running the game behind a reverse proxy without handling it in the game itself, leads to unexpected results, e.g. every player has the same IP (the IP of the webserver) and so the IP limit kicks in.

I might start working on this myself, but I think I might need some help :)

**Comment by Bios-Marcel** [comment]
I don't know much about all the networking stuff to be honest. At least on the infrastructure and tooling side not. So, I am not sure whether I am of great help with this. I also don't really enjoy the admin kind of stuff ^^

**Comment by nudelbrot** [comment]
got the same setup as @hija. have you checked the
`proxy_set_header Upgrade $http_upgrade`
`proxy_set_header Connection "upgrade"`
options of nginx? works fine for me

**Comment by hija** [comment]
Yes, but then you still need to change some settings in the lobby.html and lobby.go.

**Comment by nudelbrot** [comment]
i just changed the websocket string in lobby.html to `wss://<mydomain>/ws?id={{.LobbyID}}`

**Comment by hija** [comment]
Yes but then it’s not compatible with non ssl/tls servers anymore. This works for me too (as mentioned earlier). But we need an automated solution, because I scribble.rs should be easy to setup without people having to change the source code imho.

**Comment by nudelbrot** [comment]
ahh nvm, i overlooked this earlier. you are right, of course. adding e.g. a command line option or config file for TLS stuff would be great.

**Comment by hija** [comment]
If the reverse proxy is configured correctly you should be able to get the right settings via the X-Forwarded variables :) I will do some testing this weekend, but if you have some free time go ahead and try it out yourself :)

**Comment by nudelbrot** [comment]
as i said, it works for me (at least with two clients each running on a different computer). Tomorrow i'll try to test it with a few more people to see if it is still stable.

**Comment by hija** [comment]
Okay, I think we still misunderstand each other. 

Here is my point:
- I know it works if you change some source files (e.g. ws —> wss)
- However this is not a general fix, since the server could then not be used anymore by people without tls/ssl
- Furthermore, features like the Ip limit will most probably act wrong since they do not look at the right http header
- Changing files manually (just as you and I did) is only a temporary solution and is not suitable for non developers
- Looking at headers which get added by an reverse proxy could probably solve this problem

**Comment by Bios-Marcel** [comment]
The socket now automatically uses `wss` if the lobby URL uses the `HTTPS` protocol. However, scribble.rs itself still doesn't support SSL.

**Comment by hija** [comment]
The colon was missing in the bugfix (cf. https://www.w3schools.com/jsref/prop_loc_protocol.asp) "The protocol property sets or returns the protocol of the current URL, **including the colon (:)**."

**Comment by hija** [comment]
@Bios-Marcel Thank you :) Way smarter solution than my attempt.

One bug remains. I think, right now the IP limit is not working correctly. I try to have a look into that in the next few days :) (Maybe it's also a bad configured reverse proxy on my end)

**Comment by Bios-Marcel** [comment]
Okay, i didn't experience problems. What exactly is wrong.

**Comment by SZenglein** [comment]
@hija Could you please share your nginx config? Whatever I do, the websocket connection gets refused. Nginx is listening on 443 and scribblers running on 8080.

```
 location / {
         proxy_pass http://127.0.0.1:8080;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forward-Proto $scheme;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
         # WebSocket support (nginx 1.4)
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
}
```

**Comment by hija** [comment]
Okay, nice :) I think we need to work on fixing the IP-bug problem and then wss / tls/ssl via reverse proxy is fully supported :)

**Comment by Bios-Marcel** [comment]
Would be cool if that could be fixed. Next step would be native SSL support I guess.

**Comment by hija** [comment]
Not too sure. What is in your point the advantage for supporting SSL natively? I think for the most of the users, a reverse proxy is the way to go: they probably have a Webserver already and cannot make another server listen on port 80/443.

**Comment by Bios-Marcel** [comment]
I dunno, but it feels like making such a dependency a necessity for https isn't the right thing.

**Comment by SZenglein** [comment]
I agree, a reverse proxy is the better solution. 
The only thing to change is to check the X-Forwarded-For header and use that for the IP adress filter.

**Comment by Bios-Marcel** [comment]
Any of you gonna do a PR and test thus properly?

**Comment by SZenglein** [comment]
Would it be possible to add a field for the forwarded ip to every user and use that to check for matches in `showLobby()`? ` socket.RemoteAddr()` can never work for forwarded clients. You need a request object to access headers.

If that is not a problem I should be able to implement ssl forwarding support.

**Comment by Bios-Marcel** [comment]
I don't know. I've tried anything like that.

Looks promising: https://stackoverflow.com/questions/27234861/correct-way-of-getting-clients-ip-addresses-from-http-request

**Comment by Bios-Marcel** [comment]
Heyho, good news. In general SSL seems to work via a proxy, since the heroku container is running. (It might not work when you click it, as it only spins up when it gets traffic i think):

https://scribblers-test.herokuapp.com/

Also see https://github.com/scribble-rs/scribble.rs/issues/110

It appears there's still problems with the max IP feature, but not the way we thought.

**Comment by SZenglein** [comment]
There was no doubt SSL is not working (in fact, my instance has been using it for quite some time)

What do you mean problems are not the way we thought? Every client gets assigned the same IP, that's the only problem I could see.

**Comment by Bios-Marcel** [comment]
I see opposite, even with a limit of 1 client per IP i can connect twice. I am not sure what's going on there

**Comment by Bios-Marcel** [comment]
Okay, check out https://scribblers-test.herokuapp.com/ again. I now check the forwarding headers and use the last known IP from the HTTP requests for comparison, since we don't have access to forwarding information on the socket connections.

**Comment by SZenglein** [comment]
Yeah that was how I was doing it too. I just didn't get to testing it, haha.

**Comment by Bios-Marcel** [comment]
Well, uhm, can we close this issue then?

**Comment by SZenglein** [comment]
I haven't tested it, but if problems arise I'd rather open another issue.

**Comment by Bios-Marcel** [comment]
kk
