### ISSUE TITLE
The fill tool's effects aren't visible to other players

### ISSUE THREAD

**Issue by L-as** [scribble-rs/scribble.rs#68]
It works for the local player but others see nothing seemingly

**Comment by Bios-Marcel** [comment]
Oh weird, i had tested this. maybe i did an untested change. must be a small problem :)

**Comment by josemmc95** [comment]
You deleted "context" variable by mistake in  fill call in lobby.html (line 425).

Replace:
fill(parsed.Data.FromX * scaleDownFactor, parsed.Data.FromY * scaleDownFactor, parsed.Data.Color);

With:
fill(context, parsed.Data.FromX * scaleDownFactor, parsed.Data.FromY * scaleDownFactor, parsed.Data.Color);
