### ISSUE TITLE
Define a standard for the colors of the words

### ISSUE THREAD

**Issue by Luni-4** [scribble-rs/scribble.rs#73]
It would be useful to define a simpler standard for the colors of the words:
- Black if the written word is wrong
- Green if the written word is correct
- Swamp green but more transparent for words written by a user that has already guessed the correct word
- Red for information written by the server

**Comment by Bios-Marcel** [comment]
> Green if the written word is correct

Which scenario exactly do you mean here?

**Comment by Luni-4** [comment]
When someone guesses the word, the word appears in the chat (or in a new popup window) colored green.

**Comment by zouglou** [comment]
Having the server telling you you're correct (or anything that is not an error) in red, is not really intuitive, I think, and tends to not give "good vibes" to the user. (I lack english expressions, but you get it?)

**Comment by Luni-4** [comment]
@zouglou 

I agree with you, in fact I think the red color should be used to show ONLY server errors, because the red color is usually related to errors.

**Comment by Bios-Marcel** [comment]
ye, that kinda makes sense

**Comment by Bios-Marcel** [comment]
I'll be closing this, as I deem the current state okay.

Black - Normal messages
Green - Players that aren't guessing
Blue and Bold - Close guess messages (somewhat positive, but not quite perfect :P)
Green and bold - "Positive" server messages
Red and bold - Non positive system messages, like round over
Red, bold and "System:" prefix - non positive system messages like player kicked or settings changed
