### ISSUE TITLE
Italian words in english lobby and vice versa

### ISSUE THREAD

**Issue by nudelbrot** [scribble-rs/scribble.rs#76]
Currently the wordlists are read everytime a new lobby is created and are appended to the already existing wordlist. Wouldn't it be better to read all wordlists during the server start and use a reference / copy of the selected language in a lobby?

Currently, this is also problematic when playing multiple games with switching languages: 
You can create a english lobby and receive an italian word or vice versa.

**Comment by Bios-Marcel** [comment]
Yup, i fixed that some minutes ago, or didn't?

**Comment by nudelbrot** [comment]
ahh great, thanks

**Comment by Bios-Marcel** [comment]
If the problem persists, just reopned the issue.
