### ISSUE TITLE
Fill does not fill erased area when filling background

### ISSUE THREAD

**Issue by fabiangeissler** [scribble-rs/scribble.rs#78]
The Rubber works by applying white color. In my tested browsers (Firefox on Linux and Safari on iOS) the standard background after the clearRect call seems to be something else (transparent?). Therefore areas erased with the Rubber tool will remain white after a fill of the transparent background.

May be fixed by drawing a white rect instead of clearing it.

**Comment by fabiangeissler** [comment]
I think you forgot about the clear in the next-turn section directly below the one you just edited.

Btw. Just realized the transparent background also caused some other bugs with the floodfill that should be eliminated now too.

**Comment by Bios-Marcel** [comment]
Oh, good catch
