### ISSUE TITLE
Extended drawing capabilities

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#8]
On top of the minimal drawing capabilities mentioned in #7 , there should be additional features in order to allow the player to draw faster, more accurate and make up for his mistakes:

- [ ] Undo
- [x] Defining custom colors
- [x] Define stroke width

**Comment by Crayder** [comment]
[ ] Lines
[ ] Polygon (lines with more points)
[ ] Basic Shapes
[ ] Grid for lines and shapes

**Comment by Bios-Marcel** [comment]
I am not sure whether that is in the spirit of the game. It should still be "ugly drawings". Not that I am thinking about this, the `Ruler` feature probably makes no sense either.

**Comment by Crayder** [comment]
You're right, but I don't believe this will make them any prettier... We still have a time limit option 👉

**Comment by Bios-Marcel** [comment]
Maybe this could be something optional and disabled by default :man_shrugging: ? I wouldn't aim it at 1.0 either way.

**Comment by Crayder** [comment]
Yeah that's what I was thinking as well

**Comment by Bios-Marcel** [comment]
Guess we should be put this into another issue as well then. Together with `Ruler`

**Comment by Bios-Marcel** [comment]
I am dropping it, sticking to the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
