### ISSUE TITLE
Request for finished container at Dockerhub

### ISSUE THREAD

**Issue by lryjnks** [scribble-rs/scribble.rs#82]
Hello,

is it possible to upload a finished container at Dockerhub?

This simplifies the installation tremendously. 

Thank you and many greetings

**Comment by Bios-Marcel** [comment]
I don't quite use docker. There's an image now, it launches and you have to expose port 80. How would I make the port configurable? Is that possible?

https://hub.docker.com/repository/docker/biosmarcel/scribble.rs

**Comment by Bios-Marcel** [comment]
Actually, it doesn't matter, right? Cause you can remap the port either way :shrug:

**Comment by lryjnks** [comment]
Yeah, you can remap Ports. 
Works fine :))



Here an docker-compose example:

version: '2'
services:
  scribble:
    image: biosmarcel/scribble.rs
    ports:
      - "9443:80"
    restart: unless-stopped



Danke dir // Thanks!

**Comment by lryjnks** [comment]
Ahh I see just when I create a lobby and type "!start" in the chat probably nothing happens. 

Do you have an idea what could be the reason for this?

E.g. if you go to the container with a proxy-pass, he has a problem with the name. There you get the error message that the URL is invalid.

**Comment by Bios-Marcel** [comment]
oh, that's because the server doesnt know it's proxy URL

**Comment by Bios-Marcel** [comment]
I am not sure how to solve this.

**Comment by Bios-Marcel** [comment]
Okay ... should be fixed with the latest commit. Try out and reopen the issue if still broken.

**Comment by lryjnks** [comment]
If I access the game over the IP of the server, the chat has no function at all. I also cannot start the game.

With the proxy pass I still get the same error message.

**Comment by Bios-Marcel** [comment]
Hm, weird, what error do you get in the console? Because it works for me:

```
$ docker run -p1234:80 biosmarcel/scribble.rs
2020/03/29 15:00:06 Hwat has connected
```

I can also start and draw.

**Comment by lryjnks** [comment]
When I start it the way you did, the console output remains empty (nothing happens) and the game has the same symptoms as before (no function)


Docker Version: Docker version 19.03.6
Docker-Compose Version: docker-compose version 1.24.1

**Comment by Bios-Marcel** [comment]
The browser console

**Comment by lryjnks** [comment]
Ah.

`failed: Error during WebSocket handshake: Unexpected response code: 301`

**Comment by Bios-Marcel** [comment]
Well, then I don't know. Have you done something weird with your setup? That's a "HTTP Moved Permanently" error code I think.

**Comment by lryjnks** [comment]
When I access the game via SSL with the Proxy Pass I get this error (I understand that so far):

`Mixed Content: The page at 'serverurl/lobby?id=d73b3624-20dd-46c2-9c93-d37782e818a1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://serverurl/ws?id=d73b3624-20dd-46c2-9c93-d37782e818a1'. This request has been blocked; this endpoint must be available over WSS.`

the correct name is replaced by serverurl


But if I go directly with the server IP without SSL I get the 301. Weird.

**Comment by Bios-Marcel** [comment]
I now force the websocket to be secure if the initial connection was made via https.
try again. Make sure you use the latest commit

**Comment by lryjnks** [comment]
Thank you for your help.

Unfortunately I still get the same error over HTTPS.
Without HTTPS (directly over IP): 

`Uncaught ReferenceError: socket is not defined` 

if i reload the page:

` WebSocket connection to 'ws://serverip:1234/ws?id=007e51da-9a02-4e39-8135-a1a429115633' failed: Error during WebSocket handshake: Unexpected response code: 200`

**Comment by Bios-Marcel** [comment]
oops, i made a mistake

**Comment by Bios-Marcel** [comment]
Try again ^^

**Comment by lryjnks** [comment]
k, wait a sec.

**Comment by lryjnks** [comment]
Ok non HTTPS works fine.

HTTPS same Error

**Comment by lryjnks** [comment]
Is it perhaps because the server uses port 80 internally? Can you specify two? 80 & 443? depending on whether SSL is used or not? Then I can turn my proxy pass to 443.

**Comment by Bios-Marcel** [comment]
Can't you just map 443 to 80?

**Comment by lryjnks** [comment]
I can do that but I don't think it will have any effect. So my question is whether you can change the internal port to SSL?

**Comment by Bios-Marcel** [comment]
Well, scribblers has no SSL support by itself. And the port shpuldn't really matter.

**Comment by lryjnks** [comment]
k, thx for reply
