### ISSUE TITLE
Improve line-drawing performance

### ISSUE THREAD

**Issue by SZenglein** [scribble-rs/scribble.rs#88]
The current javascript implementation of Bresenham is not very fast. This causes problems when many events are sent, since the drawing is lagging behind.

It is especially noticeable on touch devices, where usually events are sent more frequently.

One possibility to speed up the line drawing if the manual implementation is necessary would be to use WebAssembly for drawing operations.

**Comment by SZenglein** [comment]
Update: the problem lies not in the drawing algorithm but in the buffer copying of the canvas.

**Comment by Bios-Marcel** [comment]
Could you please elaborate on your findings?

**Comment by SZenglein** [comment]
Copying only the necessary parts of the image instead of the whole image greatly improves performance. That is the main bottleneck because many small lines are drawn frequently.

I addressed this in my drawing optimizations branch.

**Comment by Bios-Marcel** [comment]
Oh, I see, I was a bit confused. The PR was merge-ready then?

**Comment by SZenglein** [comment]
In my opinion it is good to merge. The edge behavior could still be improved, but IMHO it is better than before. 

Please review it again if you notice another problem.
