### ISSUE TITLE
small explanation on word tag

### ISSUE THREAD

**Issue by kiwy42** [scribble-rs/scribble.rs#93]
Hello,  
first of all thank you for the amazing work.   
With the situation being what it is Skibble.io is now unaplayable most of the time and you have done great work.  
I would like to add French to the game and eventually add my own set of word to the game (permanently) and I'd like to understand the tag system.   
In the source code I could only find `#i` as a reference but what does other tag mean : 
 - #e
 - #h
 - #i
 - #m
 - #n
It would be awesome to have documentation for that and I will provide translated file in french when done. 
Thank you very much.

**Comment by Bios-Marcel** [comment]
Well, i initially used a list of some dictionary and the tags stand for:
impossible,
easy
medium
hard

Since not all words were easy to draw. Impossible ones get filtered out. But I left them in since I thought i'd be making a difficulties feature at some point.

**Comment by kiwy42** [comment]
Very nice,
thank you, I'll might tune this then but now I know what to tune. 
👍 
Very nice work, I hope you manage to make it as good as you want. 
I have no idea how to work with git commit and tag and versionning so I'll might be posting the french file directly here. 
I'll keep you updated, 500 word already done.

**Comment by Luni-4** [comment]
@Bios-Marcel 

Can you add your explanation to the README, please?

**Comment by kiwy42** [comment]
Here's the franch list of word more or less translated into French, I have not yet tune the difficulty, but I bet there's some mistake in it as some word are translated by some vague word.
I also didn't sort the file in alphabetical order.
https://pastebin.com/QMVfxpLp

**Comment by Bios-Marcel** [comment]
@Luni-4 I've started working on the gallery feature, therefore I won't add this to the readme, as it's outdated soon and I'll convert the wordlists over to the new system either way.

**Comment by Luni-4** [comment]
I see, thanks a lot! :)
